<?php

/**
 * @file
 * Contains jcc_case.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\file\Element\ManagedFile;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;
use Drupal\taxonomy\Entity\Term;
use Drupal\jcc_case\Ajax\ManagedFileUploadCompleteEventCommand;

/**
 * Implements hook_form_alter().
 */
function jcc_case_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form_state->getCompleteForm()['#form_id']) && $form_state->getCompleteForm()['#form_id'] == 'jcc_opinions_importer_form') {
    // Node creation and editing only customizations.
    if ((isset($form['#theme']['1']) && $form['#theme']['1'] == 'node_form')) {
      // Suppress format options from certain fields.
      if (isset($form['field_tagline'])) {
        $form['field_tagline']['widget']['#after_build'][] = '_allowed_formats_remove_option';
      }
      if (isset($form['field_feed_source'])) {
        $form['field_feed_source']['widget']['#after_build'][] = '_allowed_formats_remove_option';
      }
    }
  }
}

/**
 * Implements hook_element_info_alter().
 */
function jcc_case_element_info_alter(array &$info) {
  $info['managed_file']['#process'][] = 'jcc_case_managed_file_process';
}

/**
 * Custom ajax callback for managed files.
 *
 * Overrides \Drupal\file\Element\ManagedFile::uploadAjaxCallback()
 *
 * @see \Drupal\file\Element\ManagedFile::uploadAjaxCallback
 */
function jcc_case_managed_file_ajax_callback(array &$form, FormStateInterface $form_state) {
  // Retrieve the original response.
  $response = ManagedFile::uploadAjaxCallback($form, $form_state, \Drupal::request());

  if ($form_state->getCompleteForm()['#form_id'] == 'jcc_opinions_importer_form') {
    $response->addCommand(new ManagedFileUploadCompleteEventCommand());
  }
  return $response;
}

/**
 * Custom process callback added to managed_file elements.
 */
function jcc_case_managed_file_process(array &$element, FormStateInterface $form_state) {
  if ($form_state->getCompleteForm()['#form_id'] == 'jcc_opinions_importer_form') {
    $element['upload_button']['#ajax']['callback'] = 'jcc_case_managed_file_ajax_callback';

    if (!empty($element['fids']['#value'])) {
      foreach ($element['fids']['#value'] as $document_id) {

        $element['documents'][$document_id] = [
          '#type' => 'fieldset',
          '#collapsible' => FALSE,
        ];

        // File.
        $element['documents'][$document_id]['doc_id'] = [
          '#type' => 'hidden',
          '#value' => $document_id,
        ];
        $element['documents'][$document_id]['file'] = $element['file_' . $document_id];
        unset($element['file_' . $document_id]);

        // Document type.
        $tree_doctype = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('document_type');
        $terms_doctype = [];
        foreach ($tree_doctype as $item) {
          $terms_doctype[$item->tid] = $item->name;
        }
        $element['documents'][$document_id]['document_type'] = [
          '#type' => 'select',
          '#title' => t('Publishing Type*'),
          '#options' => $terms_doctype,
        ];

        // District.
        $tree_district = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('district');
        $terms_district = [];
        foreach ($tree_district as $item) {
          $terms_district[$item->tid] = $item->name;
        }
        $element['documents'][$document_id]['district'] = [
          '#type' => 'select',
          '#title' => t('District*'),
          '#options' => $terms_district,
        ];

        // Case number.
        $element['documents'][$document_id]['case_number'] = [
          '#type' => 'textfield',
          '#title' => t('Case Number*'),
        ];

        // Case name.
        $element['documents'][$document_id]['case_name'] = [
          '#type' => 'textfield',
          '#title' => t('Case Name*'),
        ];

        // Post date.
        $element['documents'][$document_id]['post_date'] = [
          '#title' => t('Post date*'),
          '#type' => 'date',
          '#attributes' => [
            'type' => 'date',
            'min' => '-12 months',
            'max' => '+12 months',
          ],
          '#default_value' => date('Y-m-d'),
          '#date_date_format' => 'Y/m/d',
        ];

        // Review granted flag.
        $element['documents'][$document_id]['review_granted'] = [
          '#type' => 'checkbox',
          '#title' => t('Review Granted?'),
          '#attributes' => ['class' => ['jcc-case-form__field']],
        ];

        // Related cases tags.
        $element['documents'][$document_id]['related_cases'] = [
          '#title' => t('Related Cases'),
          '#type' => 'entity_autocomplete',
          '#target_type' => 'taxonomy_term',
          '#selection_settings' => [
            'target_bundles' => ['case'],
          ],
          '#tags' => TRUE,
          '#description' => t('Optionally lookup and link related cases if available. Separate each case with a comma.'),
        ];
      }
    }
    else {
      $element['documents'] = [];
    }
  }

  return $element;
}

/**
 * Implements module theme.
 */
function jcc_case_theme() {
  return [
    'views_view__opinions' => [
      'template' => 'views-view--opinions',
      'base hook' => 'view',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for opinions posting.
 */
function jcc_case_preprocess_views_view__opinions(&$variables) {
  if (empty($variables['rows'][0]['#rows'])) {
    return;
  }

  $opinions = [];
  foreach ($variables['rows'][0]['#rows'] as $row) {
    $row = $row['#node'];
    $media = Media::load($row->field_media->target_id);
    $media_file = File::load($media->field_media_file->target_id);
    $file = [
      'uri' => $media_file->getFileUri(),
      'type' => \Drupal::service('file.mime_type.guesser')->guess($media_file->getFileUri()),
    ];
    $district = Term::load($row->field_district->target_id)->get('name')->value;
    $case = Term::load($row->field_case->target_id)->get('name')->value;
    $revision_type = NULL;
    if ($row->field_revision_type->target_id) {
      $revision_type = Term::load($row->field_revision_type->target_id)->get('name')->value;
    }

    $related_cases = [];
    foreach ($row->field_related_cases as $item) {
      $related_case = Term::load($item->target_id);
      array_push($related_cases, $related_case);
    }

    $opinion = [
      'district' => $district,
      'case' => $case,
      'revision_type' => $revision_type,
      'title' => $row->title->value,
      'url' => Url::fromRoute('entity.node.canonical', ['node' => $row->id()], ['absolute' => FALSE])->toString(),
      'review_granted' => $row->field_toggle->value,
      'post_date' => $row->field_date->value,
      'case_details' => __jcc_get_caselookup_url($district, $case),
      'file' => $file,
      'related_cases' => $related_cases,
    ];
    array_push($opinions, $opinion);
  }

  $variables['items'] = $opinions;
}

/**
 * Get taxonomy term by name from specified vocabulary.
 */
function __jcc_get_taxonomy_by_name($name, $vid) {
  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties([
    'name' => $name,
    'vid' => $vid,
  ]);

  return reset($terms);
}

/**
 * Case lookup link creator.
 */
function __jcc_get_caselookup_url($dist_name, $case_number) {
  return 'https://appellatecases.courtinfo.ca.gov/search/searchResults.cfm?dist=' .
         __jcc_get_dist_id($dist_name) . '&search=number&useSession=0&query_caseNumber=' . $case_number;
}

/**
 * Get district code for case lookup.
 */
function __jcc_get_dist_id($name) {
  switch ($name) {
    case 'Supreme Court':
      $did = 0;
      break;

    case '1st Appellate':
      $did = 1;
      break;

    case '2nd Appellate':
      $did = 2;
      break;

    case '3rd Appellate':
      $did = 3;
      break;

    case '4th Appellate, Division One':
      $did = 41;
      break;

    case '4th Appellate, Division Two':
      $did = 42;
      break;

    case '4th Appellate, Division Three':
      $did = 43;
      break;

    case '5th Appellate':
      $did = 5;
      break;

    case '6th Appellate':
      $did = 6;
      break;

    default:
      $did = -1;
  }

  return $did;
}
