_core:
  default_config_hash: Goud3RzSluZ74rDQvRN-dT7gxsuamlV9Wmh5x7qdUz8
theme: classy
defaults:
  sender: sendgrid_integration
  formatter: mime_mail
modules:
  sendgrid_integration:
    none:
      sender: sendgrid_integration
      formatter: mime_mail
