_core:
  default_config_hash: T9AghmJX0Xa-cCZPz79xWOfhli9aBvHc8XsWB2KAnpw
quick_checkout: true
anonymous_access: true
purge_finished: _never
respect_text_format: true
allowed_formats: {  }
word_count_exclude_tags: true
source_list_limit: 20
submit_job_item_on_cron: false
job_items_cron_limit: 50
