favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: sites/marin/logo.svg
  use_default: false
scheme: local
header_footer_variant: default
site_name_first: 'Superior Court of California'
site_name_second: 'County of Marin'
hat_shoe_text: 'Judicial Branch of California'
hat_shoe_url: 'https://www.courts.ca.gov'
email: ''
facebook: ''
flickr: ''
linkedin: ''
rss: ''
twitter: ''
youtube: ''
hide_was_this_helpful: 0
hide_translation: 0
show_google_translate: 0
enable_twitter_embed: 0
