<?php

/**
 * @file
 * Provides a jcc staff entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function jcc_jrn_contact_theme() {
  return [
    'jcc_staff' => [
      'render element' => 'elements',
    ],
    'jcc_cio' => [
      'render element' => 'elements',
    ],
    'jcc_officer' => [
      'render element' => 'elements',
    ],
    'jcc_ajp' => [
      'render element' => 'elements',
    ],
    'jcc_court' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for jcc staff templates.
 *
 * Default template: jcc-staff.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the jcc staff information
 *     and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_jcc_staff(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for jcc cio templates.
 *
 * Default template: jcc-cio.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the jcc cio information and
 *     any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_jcc_cio(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for jcc officer templates.
 *
 * Default template: jcc-officer.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the jcc officer information and
 *     any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_jcc_officer(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for jcc ajp templates.
 *
 * Default template: jcc-ajp.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the jcc ajp information and
 *     any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_jcc_ajp(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for jcc court templates.
 *
 * Default template: jcc-court.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the jcc court information and
 *     any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_jcc_court(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
