_core:
  default_config_hash: _nSLt4ljXD_Q-ngUBtoKUp3ZK5he5etV5BNGVUU6Q-0
extraction_method: solr_extractor
tika_extractor_configuration:
  java_path: java
  tika_path: /srv/bin/tika-app-1.18.jar
tika_server_extractor_configuration:
  scheme: http
  host: localhost
  port: '9998'
  timeout: 5
docconv_extractor_configuration:
  docconv_path: /usr/bin/docd
solr_extractor_configuration:
  solr_server: solr
python_pdf2txt_extractor_configuration:
  python_path: python
  python_pdf2txt_script: /usr/bin/pdf2txt.py
pdftotext_extractor_configuration:
  pdftotext_path: pdftotext
preserve_cache: true
