_core:
  default_config_hash: 5_2QeImE1ulfpQUE7GISOFeVuv_4Cg8_1dkHl6Hyq_I
minimum_lifetime: 86400
xsl: 1
prefetch_aliases: 1
chunk_size: auto
batch_limit: 100
path: xmlsitemap
frontpage_priority: !!float 1
frontpage_changefreq: 86400
lastmod_format: 'Y-m-d\TH:i\Z'
gz: false
clean_url: 0
disable_cron_regeneration: false
i18n_selection_mode: simple
metatag_exclude_noindex: true
