enabled_default: 0
default_challenge: recaptcha/reCAPTCHA
description: 'This question is for testing whether or not you are a human visitor and to prevent automated spam submissions.'
administration_mode: true
allow_on_admin_pages: false
add_captcha_description: false
default_validation: 1
persistence: 0
enable_stats: false
log_wrong_responses: false
_core:
  default_config_hash: h4owCOAvmyXjpFhpun7aY7qjHuz1HrHSLvjBfMhI1k4
wrong_captcha_response_message: 'The answer you entered for the CAPTCHA was not correct.'
