prohibited_blocks:
  'entity_view:node': 'entity_view:node'
  'entity_view:user': 'entity_view:user'
  page_title_block: page_title_block
  local_actions_block: local_actions_block
  local_tasks_block: local_tasks_block
  devel_switch_user: devel_switch_user
  'facet_block:content': 'facet_block:content'
  'facet_block:department': 'facet_block:department'
  'facet_block:division': 'facet_block:division'
  'facet_block:document_type': 'facet_block:document_type'
  'facet_block:event_type': 'facet_block:event_type'
  'facet_block:location_type': 'facet_block:location_type'
  'facet_block:news_type': 'facet_block:news_type'
  'facet_block:person_type': 'facet_block:person_type'
  'facet_block:subject_matter': 'facet_block:subject_matter'
  'facet_block:tags': 'facet_block:tags'
  'facet_block:topics': 'facet_block:topics'
  'facets_summary_block:summary': 'facets_summary_block:summary'
  tfa_user_login_block: tfa_user_login_block
  user_login_block: user_login_block
  geolocation_block: geolocation_block
  glossifypathexclusion: glossifypathexclusion
  related_news_custom: related_news_custom
  'views_block:announcements-block_2': 'views_block:announcements-block_2'
  'views_block:announcements-block_1': 'views_block:announcements-block_1'
  'views_block:comments_recent-block_1': 'views_block:comments_recent-block_1'
  'views_block:content_recent-block_1': 'views_block:content_recent-block_1'
  'views_block:who_s_online-who_s_online_block': 'views_block:who_s_online-who_s_online_block'
  'system_menu_block:admin': 'system_menu_block:admin'
  book_navigation: book_navigation
  'system_menu_block:devel': 'system_menu_block:devel'
  'system_menu_block:featured-links': 'system_menu_block:featured-links'
  'system_menu_block:footer': 'system_menu_block:footer'
  jcc_book_navigation_block: jcc_book_navigation_block
  'system_menu_block:main': 'system_menu_block:main'
  'system_menu_block:secondary-footer': 'system_menu_block:secondary-footer'
  'system_menu_block:tools': 'system_menu_block:tools'
  'system_menu_block:account': 'system_menu_block:account'
  openid_connect_login: openid_connect_login
  system_breadcrumb_block: system_breadcrumb_block
  'language_block:language_interface': 'language_block:language_interface'
  system_main_block: system_main_block
  system_messages_block: system_messages_block
  system_powered_by_block: system_powered_by_block
  system_branding_block: system_branding_block
  node_syndicate_block: node_syndicate_block
  'views_block:who_s_new-block_1': 'views_block:who_s_new-block_1'
  'views_exposed_filter_block:search-page_1': 'views_exposed_filter_block:search-page_1'
  jcc_hero_block: '0'
  jcc_switchboard: '0'
  'views_block:book_related_content-block_1': '0'
  'views_block:documents_by_category-block_1': '0'
  'views_block:documents_by_category-block_2': '0'
  'views_block:documents_by_category-block_3': '0'
  'views_block:faq-block': '0'
  'views_block:events-filterable_block_1': '0'
  'views_block:location-filterable_block_1': '0'
  'views_block:news-filterable_block_1': '0'
  'views_block:events-block_1': '0'
  'views_block:location-block': '0'
  'views_block:news-block_1': '0'
  'views_block:faq-block_1': '0'
_core:
  default_config_hash: 2HNsAnxJKnxlu3Oy-SBEVhLB70jb9XDVi5kB8oZ_ZTY
