display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        fid:
          separator: ', '
        prefix:
          label: Prefijo
        value:
          label: Correspondencias
        suffix:
          label: Sufijo
        nothing:
          alter:
            text: Editar
        dropbutton:
          label: Operaciones
      arguments:
        fid:
          exception:
            title: Todo(s)
  block_1:
    display_title: Bloque
