<?php

/**
 * @file
 * Primary module hooks for case lookup integrations.
 */

use Drupal\file\Entity\File;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_preprocess_HOOK() for appellate legacy project.
 */
function jcc_appellate_legacy_project_preprocess_views_view__justices_appellate_court_legacy_project(&$variables) {
  if (empty($variables['rows'][0]['#rows'])) {
    return;
  }

  // Build the array of accordion items.
  global $base_url;
  $interviews = [];
  foreach ($variables['rows'][0]['#rows'] as $row) {
    $media = $row['#row']->_entity;
    $name = $media->get('name')->value;
    $district = $media->get('jcc_section')->target_id ? Term::load($media->get('jcc_section')->target_id)->get('name')->value : '';
    $profile = \Drupal::service('path_alias.manager')->getAliasByPath($media->get('field_media_caption')->value);
    $file = File::load($media->get('field_media_file')->target_id);
    $transcript = '';
    if ($file) {
      $transcript = \Drupal::service('file_url_generator')->generateAbsoluteString($file->uri->value);
    }
    $video = \Drupal::entityTypeManager()->getViewBuilder('media')->view($media);
    $interview = [
      'district' => $district,
      'name' => $name,
      'video' => $video,
      'profile' => $base_url . $profile,
      'transcript' => $transcript,
    ];
    array_push($interviews, $interview);
  }

  // Group justices by district.
  $justices = [];
  foreach ($interviews as $interview) {
    if ($interview['district']) {
      $district = $interview['district'];
      $justices[$district][] = $interview;
    }
    else {
      $justices['Unassigned'][] = $interview;
    }
  }

  $variables['justices'] = $justices;
}
