_core:
  default_config_hash: xu0yG13sSQJcXrOJJqsn44W_hUWAIFHVlphrzxT2ycU
page_title: Sitemap
message:
  value: ''
  format: plain_text
plugins:
  book:
    enabled: false
    weight: 0
  'menu:admin':
    enabled: false
    weight: 0
    settings:
      title: Administration
      show_disabled: false
  'vocabulary:media_image_category':
    enabled: false
    weight: 0
    settings:
      title: 'Media image category'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:media_tags':
    enabled: false
    weight: 0
    settings:
      title: 'Media tags'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:multimedia_type':
    enabled: false
    weight: 0
    settings:
      title: 'Multimedia Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:news_type':
    enabled: false
    weight: 0
    settings:
      title: 'News Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:person_type':
    enabled: false
    weight: 0
    settings:
      title: 'Person Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'menu:account':
    enabled: false
    weight: 0
    settings:
      title: 'User account menu'
      show_disabled: false
  'menu:featured-links':
    enabled: false
    weight: 0
    settings:
      title: 'Featured Links'
      show_disabled: false
  'vocabulary:matters_served':
    enabled: false
    weight: 0
    settings:
      title: 'Matters Served'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'menu:footer':
    enabled: false
    weight: 0
    settings:
      title: Footer
      show_disabled: false
  'menu:hat':
    enabled: false
    weight: 0
    settings:
      title: Hat
      show_disabled: false
  'menu:main':
    enabled: true
    weight: 0
    settings:
      title: 'Main navigation'
      show_disabled: false
  'menu:secondary-footer':
    enabled: false
    weight: 0
    settings:
      title: 'Secondary Footer'
      show_disabled: false
  'menu:shoe':
    enabled: false
    weight: 0
    settings:
      title: Shoe
      show_disabled: false
  'menu:tools':
    enabled: false
    weight: 0
    settings:
      title: Tools
      show_disabled: false
  'vocabulary:media_file_category':
    enabled: false
    weight: 0
    settings:
      title: 'Media file category'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:location_type':
    enabled: false
    weight: 0
    settings:
      title: 'Location Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:subject_matter':
    enabled: false
    weight: 0
    settings:
      title: 'Subject Matter'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:case_status':
    enabled: false
    weight: 0
    settings:
      title: 'Case Status'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:tags':
    enabled: false
    weight: 0
    settings:
      title: Tags
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:topics':
    enabled: false
    weight: 0
    settings:
      title: Topics
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:user_groups':
    enabled: false
    weight: 0
    settings:
      title: 'User groups'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:case_category':
    enabled: false
    weight: 0
    settings:
      title: 'Case Category'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:case_number':
    enabled: false
    weight: 0
    settings:
      title: 'Case Number'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:case_party_type':
    enabled: false
    weight: 0
    settings:
      title: 'Case Party Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:case_subtype':
    enabled: false
    weight: 0
    settings:
      title: 'Case Subtype'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:hearing_type':
    enabled: false
    weight: 0
    settings:
      title: 'Hearing Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:case_type':
    enabled: false
    weight: 0
    settings:
      title: 'Case Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:department':
    enabled: false
    weight: 0
    settings:
      title: Department
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:division':
    enabled: false
    weight: 0
    settings:
      title: Division
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:document_type':
    enabled: false
    weight: 0
    settings:
      title: 'Document Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:event_type':
    enabled: false
    weight: 0
    settings:
      title: 'Event Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:glossary':
    enabled: false
    weight: 0
    settings:
      title: Glossary
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  frontpage:
    enabled: false
    weight: 0
    settings:
      title: 'Front page'
      rss: /rss.xml
include_css: true
