third_party_settings:
  field_group:
    group_content:
      label: Contenido
content:
  field_brow:
    third_party_settings:
      maxlength:
        maxlength_js_label: 'Contenido limitado en @limit caracteres, quedan: <strong>@remaining</strong>'
  field_components:
    settings:
      title: Contenido
  field_link:
    third_party_settings:
      maxlength:
        maxlength_js_label: 'Contenido limitado en @limit caracteres, quedan: <strong>@remaining</strong>'
