tips:
  search-api-index-fields-add:
    label: 'Añadir campos'
    body: 'Con el botón "Añadir campos" se pueden añadir campos adicionales a este índice.'
  search-api-index-fields-label:
    label: Etiqueta
    body: 'Una etiqueta para el campo que se utilizará para referirse al campo en la mayoría de los lugares de la interfaz de usuario.'
  search-api-index-fields-machine-name:
    label: 'Nombre de sistema'
  search-api-index-fields-type:
    label: Tipo
  search-api-index-fields-boost:
    label: Boost
  search-api-index-fields-edit:
    label: 'Editar campo'
  search-api-index-fields-remove:
    label: 'Eliminar campo'
  search-api-index-fields-submit:
    label: 'Guardar cambios'
  search-api-index-fields-cancel:
    label: 'Cancelar cambios'
