label: 'Procesadores utilizados para este índice'
tips:
  search-api-index-processors-introduction:
    label: 'Procesadores utilizados para este índice'
  search-api-index-processors-enable:
    label: 'Habilitar procesadores'
  search-api-index-processors-weights:
    label: 'Orden de procesador'
  search-api-index-processors-settings:
    label: 'Opciones de procesador'
    body: 'Algunos procesadores tienen una configuración adicional disponible, que puede cambiar aquí.'
