label: 'Biblioteca de medios'
description: 'Buscar y administrar medios.'
display:
  default:
    display_title: 'Por defecto'
    display_options:
      title: Multimedia
      fields:
        media_bulk_form:
          action_title: Acci칩n
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por p치gina'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      exposed_form:
        options:
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      empty:
        area_text_custom:
          content: 'No hay medios disponibles.'
      filters:
        status:
          group_info:
            label: Publicado
            group_items:
              1:
                title: Publicado
              2:
                title: 'Sin publicar'
        name:
          expose:
            label: Nombre
        langcode:
          expose:
            label: Idioma
  page:
    display_title: P치gina
    display_options:
      fields:
        media_bulk_form:
          action_title: Acci칩n
  widget:
    display_options:
      arguments:
        bundle:
          exception:
            title: Todo(s)
      filters:
        name:
          expose:
            label: Nombre
  widget_table:
    display_options:
      fields:
        thumbnail__target_id:
          label: Miniatura
        name:
          label: Nombre
        uid:
          label: Autor
        changed:
          label: Actualizado
      arguments:
        bundle:
          exception:
            title: Todo(s)
      filters:
        name:
          expose:
            label: Nombre
