display:
  default:
    display_title: 'Por defecto'
    display_options:
      fields:
        field_date_time:
          label: Fecha
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      exposed_form:
        options:
          submit_button: Buscar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
  block_1:
    display_title: Bloque
    display_options:
      exposed_form:
        options:
          submit_button: Buscar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
  tentative_rulings:
    display_title: Página
