display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          text_input_required: 'Seleccione cualquier filtro y pulse Aplicar para ver los resultados'
          bef:
            general:
              secondary_label: 'Opciones avanzadas'
      pager:
        options:
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
  news_list:
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          text_input_required: 'Seleccione cualquier filtro y pulse Aplicar para ver los resultados'
          bef:
            general:
              secondary_label: 'Opciones avanzadas'
