display:
  default:
    display_title: Máster
    display_options:
      fields:
        created:
          label: Creado
        view_webform_submission:
          label: Operaciones
      pager:
        options:
          tags:
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      arguments:
        in_draft:
          exception:
            title: Todo(s)
  embed_administer:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Acción
        created:
          label: Creado
        operations:
          label: Operaciones
  embed_manage:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Acción
        created:
          label: Creado
        view_webform_submission:
          label: Operaciones
        edit_webform_submission:
          label: Operaciones
  embed_review:
    display_options:
      fields:
        created:
          label: Creado
        view_webform_submission:
          label: Operaciones
