display:
  default:
    display_title: Máster
    display_options:
      fields:
        title:
          label: Nombre
        field_importer_date:
          label: Fecha
        field_importer_department:
          label: Departamento
        field_importer_location:
          label: Ubicación
      pager:
        options:
          tags:
            next: 'Siguiente >'
            previous: '‹ Anterior'
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            offset_label: Desplazamiento
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
  events:
    display_title: Bloque
