display:
  default:
    display_title: 'Por defecto'
    display_options:
      fields:
        title:
          label: Título
        changed:
          label: Modificado
      pager:
        options:
          tags:
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          text_input_required: 'Seleccione cualquier filtro y pulse Aplicar para ver los resultados'
          bef:
            general:
              secondary_label: 'Opciones avanzadas'
  page_1:
    display_title: Página
