label: Buscar
display:
  default:
    display_title: Máster
    display_options:
      title: Buscar
      pager:
        options:
          tags:
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      exposed_form:
        options:
          submit_button: Buscar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          bef:
            general:
              secondary_label: 'Opciones avanzadas'
  search:
    display_title: Página
