settings:
  default_submit_button_label: Aplicar
  default_reset_button_label: Restablecer
  default_preview_next_button_label: Preview
  default_preview_label: Preview
element:
  default_more_title: Más
