# Rename this file to .lando.yml to use, or delete if you already have one.
# Named start.lando.yml to not conflict with projects installed with lando mw install.

# project_code: cmm, apb_d7, etc.
name: tc

# drupal8 | drupal7 | wordpress
recipe: drupal8

config:
  # default: web | lightning: docroot
  webroot: web

  php: '7.3'

  database: mariadb

  composer_version: '1.10.15'

  # Optionally activate xdebug
  #
  # If you are having trouble getting xdebug to work please see:
  # https://docs.devwithlando.io/services/php.html#using-xdebug
  #xdebug: true

proxy:
  appserver:
    # Default (Base for starting multisites.)
    - default.lndo.site
    # Multi Sites (Don't forget to update web/sites/sites.php)
    # - deprep.lndo.site
    - inyo.lndo.site
    # - md.lndo.site
    # - newsroom.lndo.site
    - sc.lndo.site
    - slo.lndo.site
    - slo2.lndo.site
    # - webservices.lndo.site

# Additional services and features.
services:
  # Theme.
  node-cli:
    type: compose
    services:
      image: node:13.13.0
      # Required. See Below
      command: docker-php-entrypoint apache2-foreground
      volumes:
        - .:/app
  dbslo:
    type: mysql:5.7
    creds:
      user: drupal8
      password: drupal8
      database: drupal8
  # dbnewsroom:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal8
  #     password: drupal8
  #     database: drupal8
  # dbdeprep:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal8
  #     password: drupal8
  #     database: drupal8
  # dbmd:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal8
  #     password: drupal8
  #     database: drupal8
  # dbwebservices:
  #   type: mysql:5.7
  #   creds:
  #     user: drupal8
  #     password: drupal8
  #     database: drupal8
  dbsc:
    type: mysql:5.7
    creds:
      user: drupal8
      password: drupal8
      database: drupal8
  dbinyo:
    type: mysql:5.7
    creds:
      user: drupal8
      password: drupal8
      database: drupal8
  dbslo2:
    type: mysql:5.7
    creds:
      user: drupal8
      password: drupal8
      database: drupal8

  # solr:
  #   # Use solr version 5.5
  #   type: solr:5.5
  #   # Optionally allow access to the database at localhost:9999
  #   # You will need to make sure port 9999 is open on your machine
  #   #
  #   # You can also set `portforward: true` to have Lando dynamically assign
  #   # a port. Unlike specifying an actual port setting this to true will give you
  #   # a different port every time you restart your app
  #   portforward: 9999
  #   # Optionally declare the name of the solr core.
  #   # This setting is only applicable for versions 5.5 and above
  #   core: freedom
  #   config:
  #     conf: web/modules/contrib/search_api_solr/solr-conf/5.x

  appserver:
    extras:
     # Apache Tika
     - apt-get update -y
     - apt-get install -y openjdk-8-jre-headless
     - apt-get install -y openjdk-8-jdk
     - mkdir -p /app/srv/bin && cd /app/srv/bin
     - cd /app/srv/bin && curl -OL http://archive.apache.org/dist/tika/tika-app-1.18.jar
     - apt-get remove openjdk-8-jdk -y

# Custom Lando commands
tooling:
  dbget:
    description: "dbget [drush-alias]\tPull the database for alias. i.e. lando dbget @slo.live"
    service: appserver
    cmd: scripts/dbget.sh
  feature:docs:
    description: "Show documentation for managing features on this project. FEATURES.md"
    service: appserver
    cmd: clear && scripts/feature_sync.sh docs
  feature:enable:
    description: "lando feature:enable [module]\t\t\tEnable a new feature on all multisites."
    service: appserver
    cmd: scripts/feature_sync.sh enable
  feature:sync:
    description: "lando feature:sync [site code (oc)]\tSync latest feature updates to all multisites."
    service: appserver
    cmd: scripts/feature_sync.sh sync
  fresh:
    description: "Run all the things to get local to a fresh state for this branch. (Checkout master branch first if starting a new feature.)
      \n -h\tShow this help message.
      \n -f\t[path/to/sql] - Import a database file.
      \n -l\t[URI] for drush commands. Target specific multisites.
      \n  \tSee available appserver proxies in .lando.yml
      \n  \tOR urls in lando info --service=appserver."
    cmd:
      - appserver: rm -f /app/data/.*.fresh && true
      - appserver: scripts/fresh.sh
      - node-cli: scripts/fresh.sh
      - appserver: scripts/fresh.sh
  multisite:
    service: appserver
    description: "Helper for creating new multisites.
      \n FIRST take these steps: ([new] = short site code like slo)
      \n  - create new proxy in .lando.yml tc-[new].lndo.site
      \n  - create new db service in .lando.yml db[new]
      \n  - lando rebuild
      \n THEN run (lando multisite [new])"
    cmd: scripts/install.sh
  node:
    service: node-cli
  npm:
    service: node-cli
  phpcbf:
    service: appserver
    description: "lando phpcbf [path]\tCode Beautification. (Auto fix coding standards.)"
    cmd: /app/vendor/bin/phpcbf --config-set installed_paths /app/vendor/drupal/coder/coder_sniffer && /app/vendor/bin/phpcbf -p --standard=Drupal,DrupalPractice --extensions=php,inc,profile,module,install,profile
  phpcs:
    service: appserver
    description: "lando phpcs [path]\tCode Sniffer. (Check coding standards.)"
    cmd: /app/vendor/bin/phpcs --config-set installed_paths /app/vendor/drupal/coder/coder_sniffer && /app/vendor/bin/phpcs -p --standard=Drupal,DrupalPractice --extensions=php,inc,profile,module,install,profile
  phpmd:
    service: appserver
    description: "lando phpmd [path] [format] [ruleset]\tMess Detector."
    cmd: /app/vendor/bin/phpmd
  reset:
    service: appserver
    description: "lando reset -l [alias]\tRuns updb, cr, cim, uli \n Reset your local after a build or db install."
    cmd:
      - drush updb -y
      - drush cim -y
      - drush cr
  tb:
    service: node-cli
    description: "Theme: Build - `tb [theme_name]` Build poduction theme assets."
    cmd:
      - /app/scripts/theme.sh -b
  tb:all:
    service: node-cli
    description: "Theme: Build All - `tb:all` Build all themes in the themes/custom directory."
    cmd: /app/scripts/theme.sh -a
  th:
    service: appserver
    description: "Help information for theme management."
    cmd: /app/scripts/theme.sh -h
  ti:
    service: node-cli
    description: "Theme: Install - `ti [theme_name]` (npm install)"
    cmd:
      - /app/scripts/theme.sh -i
      - /app/scripts/theme.sh -b
  tw:
    service: node-cli
    description: "Theme: Watch `tw [theme_name]`"
    cmd:
      - /app/scripts/theme.sh -w
  ts:
    service: appserver
    description: "Theme: Sub - `ts [Theme Name]` Create subtheme from JCC Base"
    cmd:
      - drush --include=/app/web/themes/custom/jcc_base jcc_base:create
  # Docker is extra slow with xdebug enabled. Turn it on and off as needed without rebuilding.
  # xdebug: https://github.com/lando/lando/issues/1668#issuecomment-507191275
  xon:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xoff:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root

env_file:
  - .env
