<?php

/**
 * @file
 * Hooks and functions for the JCC Video Embed module.
 */

use Drupal\video_embed_field\ProviderPluginManager;

/**
 * Implements hook_video_embed_field_providers_alter().
 *
 * Adds Akamai as a valid video provider.
 */
function jcc_video_embed_wistia_akamai_video_embed_field_providers_alter(array &$providers) {
  $providers['akamai'] = [
    'id' => 'akamai',
    'title' => t('Akamai'),
    'description' => t('Embed videos from Akamai CDN.'),
    'class' => 'Drupal\jcc_video_embed_wistia_akamai\Plugin\video_embed_field\Provider\Akamai',
  ];
}
