_core:
  default_config_hash: L7V6wJjsvFNqjJIDquHAS4nVxatziYJ8aWrli0zhDqo
backend: local_server
remote_protocol: https
allowed_schemes:
  - private
template_scheme: public
local_service_endpoint: 'https://jcc-fillpdf.azurewebsites.net'
shell_locale: en_US.UTF-8
