_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 9d1bac6c-3991-4336-bf21-a727a8b7093c
name: 'Superior Court of California | County of San Bernardino'
mail: no-reply@courtinfo.ca.gov
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
