definitions:
  contact__site_page:
    enabled: false
    menu_name: footer
    parent: ''
    expanded: false
    weight: 0
  jcc_tc__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: 0
  user__logout:
    menu_name: main
    parent: ''
    weight: 10
    expanded: false
    enabled: true
_core:
  default_config_hash: 1XnK_3CTdUypNlenZguDPgwe9cj9R0H4n2MV2rkTzOk
