_core:
  default_config_hash: 2HNsAnxJKnxlu3Oy-SBEVhLB70jb9XDVi5kB8oZ_ZTY
prohibited_blocks:
  'entity_view:node': 'entity_view:node'
  'entity_view:user': 'entity_view:user'
  page_title_block: page_title_block
  local_actions_block: local_actions_block
  local_tasks_block: local_tasks_block
  devel_switch_user: devel_switch_user
  geolocation_block: geolocation_block
  'system_menu_block:admin': 'system_menu_block:admin'
  book_navigation: book_navigation
  'system_menu_block:devel': 'system_menu_block:devel'
  'system_menu_block:featured-links': 'system_menu_block:featured-links'
  'system_menu_block:footer': 'system_menu_block:footer'
  jcc_book_navigation_block: jcc_book_navigation_block
  'system_menu_block:main': 'system_menu_block:main'
  'system_menu_block:secondary-footer': 'system_menu_block:secondary-footer'
  'system_menu_block:tools': 'system_menu_block:tools'
  'system_menu_block:account': 'system_menu_block:account'
  system_breadcrumb_block: system_breadcrumb_block
  'language_block:language_interface': 'language_block:language_interface'
  system_main_block: system_main_block
  system_messages_block: system_messages_block
  system_powered_by_block: system_powered_by_block
  system_branding_block: system_branding_block
  node_syndicate_block: node_syndicate_block
  'views_block:who_s_new-block_1': 'views_block:who_s_new-block_1'
  'facet_block:content_type': '0'
  'facet_block:division_taxonomy_term_name': '0'
  tfa_user_login_block: '0'
  user_login_block: '0'
  jcc_hero_block: '0'
  'views_block:announcements-block_1': '0'
  'views_block:events-block_1': '0'
  'views_block:location-block': '0'
  'views_block:comments_recent-block_1': '0'
  'views_block:content_recent-block_1': '0'
  'views_block:news-block_1': '0'
  'views_block:who_s_online-who_s_online_block': '0'
  openid_connect_login: '0'
