_core:
  default_config_hash: XLYhpCTHj9sZf2TuFeHtWpgUlz6dSUVx7fstTdqFkCs
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
  domains:
    en: ''
    es: ''
selected_langcode: site_default
