_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: current
defaults:
  sender: sendgrid_integration
  formatter: sendgrid_integration
modules:
  sendgrid_integration:
    none:
      sender: sendgrid_integration
      formatter: sendgrid_integration
