_core:
  default_config_hash: PMB0aJrA5afgG0swQ81b31o6ax8keNE22FKGnQH81EQ
langcode: en
display_denied_message: true
access_denied_message: 'Access denied. You must log in to view this page.  If you do not have an account, please contact jcart@jud.ca.gov for assistance.'
access_denied_message_type: error
redirect_authenticated_users_to: /home
user_login_path: /user/login
default_redirect_code: 307
destination_parameter_override: ''
match_noredirect_pages: ''
redirect_to_destination: true
