<?php

/**
 * @file
 * Primary module hooks for JCC Featured Links module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

define('JCC_FEATURED_LINKS_MAX', 8);

/**
 * Implements hook_theme().
 */
function jcc_featured_links_theme($existing, $type, $theme, $path) {
  return [
    'menu__extras__featured_links' => [
      'render element' => 'content',
      'base hook' => 'menu'
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function jcc_featured_links_preprocess_menu(&$variables) {
  if ($variables['menu_name'] == 'featured_links') {
    // Limit total number of links to render.
    $variables['items'] = array_slice($variables['items'], 0, JCC_FEATURED_LINKS_MAX);
  }
}
