definitions:
  contact__site_page:
    weight: -45
    menu_name: footer
    parent: ''
    expanded: false
    enabled: false
_core:
  default_config_hash: DYhkNTiXUVcO9Yq3_I1cMCF-k2KVeNvjhfHjniqp1-Q
