name: 'Rules of court config'
description: 'Current configuration setup for Rules of Courts'
type: module
core_version_requirement: '^9.4 || ^10'
dependencies:
  - allowed_formats
  - draggableviews
  - eck
  - entity_print
  - field
  - jcc_tc2_all_immutable_config
  - maxlength
  - node
  - path
  - pathauto
  - taxonomy
  - text
  - tmgmt_content
  - user
  - views
  - views_bulk_operations
version: '1.0'
package: 'JCC TC2'
