_core:
  default_config_hash: RWJRLc5d7n0hjhwi74q6eHDIQCH3yUGKSfRRAnzUYz0
hash_key: auHash
duration: 172800
cleanup_expired_tokens: true
cleanup_expired_tokens_period: '-2 weeks'
modify_http_headers: {  }
