_core:
  default_config_hash: qDWhE2GdPTLybPFvbv5AkLj576BaroqLTjoSf1Bq6VU
icons_path: libraries/courtyard-artifact/2.x/source/_patterns/01-atoms/icon/icons.svg
icon_sets: "fa\r\nexperimental-white\r\nexperimental-dark\r\nline-white\r\nline-dark"
