_core:
  default_config_hash: 33e2YFZCFRvnoUgN6QOUat8Gwx8FTdyLfsEdCnQK-1g
icon_base_uri: 'public://media-icons/generic'
iframe_domain: ''
oembed_providers_url: 'https://oembed.com/providers.json'
standalone_url: true
recursive_render_depth: '200'
