_core:
  default_config_hash: t8ntt8z66AOjjRtZ5qpaHQEV8i6a47MxMtBp9uJzASw
first_day: 0
country:
  default: US
timezone:
  default: America/Los_Angeles
  user:
    configurable: true
    default: 0
    warn: false
