features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: sites/modoc/logo.svg
favicon:
  use_default: true
scheme: base
header_footer_variant: default
site_name_first: ''
site_name_second: ''
hat_shoe_text: ''
hat_shoe_url: ''
email: ''
facebook: ''
flickr: ''
linkedin: ''
rss: ''
twitter: ''
youtube: ''
hide_translation: 1
show_google_translate: 1
