<?php

use Drupal\views\Views;

/**
 * @file
 * Primary module hooks for jcc_newslinks module.
 */

/**
 * Implements hook_cron().
 *
 * Automatically unpromote NewsLinks after the 4th ranking that
 * are older than 2 weeks.
 */
function jcc_newslinks_cron() {
  // Default to 0 for 4th item sorting weight.
  $fourth_sorting_weight = 0;
  // First find the field_sorting_weight of the 4th item.
  $queryNid = \Drupal::entityQuery('node')
    ->condition('type', 'news')
    ->condition('field_news_type.entity:taxonomy_term.name', 'NewsLink')
  // Items that only are promoted.
    ->condition('promote', TRUE)
  // Get the 4th item; indexed at 0.
    ->range(3, 1)
    ->sort('field_sorting_weight', 'ASC');
  // Get the nid from the query.
  $nid = $queryNid->execute();

  foreach ($nid as $record) {
    // Then load the node and get 4th sorting weight value.
    $node_storage = \Drupal::entityTypeManager()->getStorage('node');
    $node = $node_storage->load($record);
    $fourth_sorting_weight = intval($node->get('field_sorting_weight')->getString());
  }

  // Unpromote newslinks after 14 days.
  $oldTimeValue = time() - (14 * 24 * 60 * 60);
  $queryUnpromote = \Drupal::entityQuery('node')
    ->condition('type', 'news')
    ->condition('field_news_type.entity:taxonomy_term.name', 'NewsLink')
    // Items that only are promoted.
    ->condition('promote', TRUE)
    // Items older than 14 days ago.
    ->condition('created', $oldTimeValue, '<')
    // Items older than 4th ranking.
    ->condition('field_sorting_weight', $fourth_sorting_weight, '>');
  $unpromoteItems = $queryUnpromote->execute();

  $unpromoteQueue = \Drupal::queue('newslinks_unpromote_queue');
  foreach ($unpromoteItems as $result) {
    $item = (object) ['nid' => $result];
    $unpromoteQueue->createItem($item);
  }
  $unpromoteMessage = count($unpromoteItems) . ' newslinks are queued to be unpromoted';
  \Drupal::logger('jcc_newslinks')->notice($unpromoteMessage);

  // Archive newslink drafts after 5 days.
  $draftTimeLimit = time() - (5 * 24 * 60 * 60);
  $queryDrafts = \Drupal::entityQuery('node')
    ->condition('type', 'news')
    ->condition('field_news_type.entity:taxonomy_term.name', 'NewsLink')
    // Items that are in draft.
    ->condition('moderation_state', 'draft')
    // Items older than 5 days ago.
    ->condition('created', $draftTimeLimit, '<');
  $draftItems = $queryDrafts->execute();

  $archiveQueue = \Drupal::queue('newslinks_archive_queue');
  foreach ($draftItems as $result) {
    $item = (object) ['nid' => $result];
    $archiveQueue->createItem($item);
  }
  $archiveMessage = count($draftItems) . ' newslink drafts are queued to be archived';
  \Drupal::logger('jcc_newslinks')->notice($archiveMessage);

  // Purge media from archived newslinks after 10 days.
  // Process in batches to avoid time limit concerns.
  $archiveTimeLimit = time() - (10 * 24 * 60 * 60);
  $queryArchived = \Drupal::entityQuery('node')
    ->condition('type', 'news')
    ->condition('field_news_type.entity:taxonomy_term.name', 'NewsLink')
    // Items that are archived.
    ->condition('moderation_state', 'archived')
    // Items older than 10 days ago.
    ->condition('created', $archiveTimeLimit, '<')
    // Items have media image entities.
    ->exists('field_images')
    ->range(0, 200);
  $purgeItems = $queryArchived->execute();

  $purgeQueue = \Drupal::queue('newslinks_archive_queue');
  foreach ($purgeItems as $result) {
    $item = (object) ['nid' => $result];
    // Check in case item is still in queue.
    $queue_item_exists = \Drupal::database()->query('SELECT item_id  FROM {queue} WHERE name = :name AND data LIKE :nid LIMIT 1',
      [
        ':name' => 'newslinks_archive_queue',
        ':nid' => '%"' . $item->nid . '%',
      ]
    )->fetchField();
    // Only add new items.
    if (!$queue_item_exists) {
      $purgeQueue->createItem($item);
    }
  }

  $purgeMessage = count($purgeItems) . ' archived newslinks are queued for media purge';
  \Drupal::logger('jcc_newslinks')->notice($purgeMessage);

  // Old newslinks item Purge (Batch of 100 nodes)
  $view = Views::getView('newslinks_expiration');
  $view->setDisplay('default');
  $view->execute();
  $view_result = $view->result;

  if (!empty($view_result)) {
    $storage_handler = \Drupal::entityTypeManager()->getStorage("node");
    $nodes_to_delete = [];
    foreach ($view->result as $row) {
      $nodes_to_delete[] = $row->nid;
    }
    \Drupal::logger('jcc_newslinks')->notice('Purged newslinks with nids: ' . implode(', ', $nodes_to_delete));
    $entities = $storage_handler->loadMultiple($nodes_to_delete);
    $storage_handler->delete($entities);
  }
}
