theme: classy
defaults:
  sender: sendgrid_integration
  formatter: mime_mail
_core:
  default_config_hash: wa6URNSENtSS9gNbZTQf5poLKHgzu1Hz2GH38Nxci9g
modules:
  sendgrid_integration:
    none:
      formatter: mime_mail
      sender: sendgrid_integration
