_core:
  default_config_hash: xG-M6wrdMJhjfod4XLo5uXFM6-AerFMiXrfX_ykr4NY
iconset: social-icons--square
services:
  facebook: facebook
  x: x
  email: email
  linkedin: linkedin
width: 30px
radius: 3px
print_css: ''
facebook_app_id: ''
node_field: false
height: 30px
