_core:
  default_config_hash: 6Ka3T1c-CIjEUO1Q64NXKksLthkMhj53a6zy4RJBtkc
verbose: 1
types:
  block_content: {  }
  comment: {  }
  contact_message: {  }
  content_moderation_state: {  }
  crop: {  }
  entity_embed_fake_entity: {  }
  feeds_subscription: {  }
  feeds_feed: {  }
  file: {  }
  media: {  }
  menu_link_content: {  }
  node:
    '*': '*'
  path_alias: {  }
  redirect: {  }
  search_api_task: {  }
  taxonomy_term: {  }
  user: {  }
  paragraph: {  }
types_translation_lock: {  }
types_js_lock:
  - node
form_op_lock:
  block_content:
    mode: 0
    values: {  }
  comment:
    mode: 0
    values: {  }
  contact_message:
    mode: 0
    values: {  }
  content_moderation_state:
    mode: 0
    values: {  }
  crop:
    mode: 0
    values: {  }
  entity_embed_fake_entity:
    mode: null
    values: {  }
  feeds_subscription:
    mode: null
    values: {  }
  feeds_feed:
    mode: 0
    values: {  }
  file:
    mode: null
    values: {  }
  media:
    mode: 0
    values: {  }
  menu_link_content:
    mode: 0
    values: {  }
  node:
    mode: 0
    values: {  }
  path_alias:
    mode: 0
    values: {  }
  redirect:
    mode: 0
    values: {  }
  search_api_task:
    mode: null
    values: {  }
  taxonomy_term:
    mode: 0
    values: {  }
  user:
    mode: 0
    values: {  }
  paragraph:
    mode: 0
    values: {  }
