_core:
  default_config_hash: 1XnK_3CTdUypNlenZguDPgwe9cj9R0H4n2MV2rkTzOk
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: false
  jcc_tc__front_page:
    menu_name: main
    parent: ''
    weight: 0
    expanded: false
    enabled: false
