_core:
  default_config_hash: 10U2elPObg2uslkYqiSfJZep2qeZaODdFTBivnKalC8
applies_admin_routes: true
include_invalid_paths: true
excluded_paths: ''
replaced_titles: ''
custom_paths: ''
include_home_segment: true
home_segment_title: Home
home_segment_keep: false
include_title_segment: true
title_from_page_when_available: true
title_segment_as_link: false
segments_separator: null
use_menu_title_as_fallback: true
use_page_title_as_menu_title_fallback: false
remove_repeated_segments: true
language_path_prefix_as_segment: false
absolute_paths: false
hide_single_home_item: true
term_hierarchy: false
