_core:
  default_config_hash: SmvBk92BEAUiEXDQEmBvuH0fRx-BmSLB3Y7_eqNPH-A
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public://NewsroomDrupalBanner Blue_0.png'
  use_default: false
facebook: 'https://www.facebook.com/CaliforniaCourts/'
twitter: 'https://twitter.com/CalCourts'
youtube: 'https://www.youtube.com/californiacourts'
