_core:
  default_config_hash: 6ynzArDptMgNVdAPodaYCxp1_iI3gS-5vLfl5M7H13M
hide_media_library_media_tab: true
hide_media_library_files_tab: true
hide_admin_toolbar_links: true
enable_combined_upload: false
combined_upload_media_types:
  file: '0'
  image: '0'
  menu_icons: '0'
