_core:
  default_config_hash: f4sH8CGbEMFQXKFoGeaHbmIP_f6cOTi02EeFhHSbYyo
langcode: en
page_title: Sitemap
message:
  value: ''
  format: restricted_html
show_front: true
show_titles: true
show_books: {  }
books_expanded: true
show_menus: {  }
show_menus_hidden: false
show_vocabularies: {  }
show_description: true
show_count: true
vocabulary_show_links: false
vocabulary_depth: -1
term_threshold: 0
forum_threshold: -1
rss_front: rss.xml
show_rss_links: 1
rss_taxonomy: -1
css: true
order:
  front: -50
