name: 'California Courts Newsroom'
mail: no-reply@courtinfo.ca.gov
slogan: ''
page:
  403: ''
  404: ''
  front: /node/882
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: 39xtgXrOgWf5RNUvb1GEpd2NaWLBt_9KL4Ue2DG3NJk
uuid: 5444d4ac-162d-4a56-913f-46fe88da9f3a
