<?php

/**
 * @file
 * jcc_auto_archive module file.
 */

/**
 * Implements hook_help().
 */
function jcc_auto_archive_module_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.jcc_auto_archive_module':
      return '<p>' . t('This is the help text for the jcc_auto_archive Module.') . '</p>';
  }
}

/**
 * Implements hook_cron().
 */
function jcc_auto_archive_cron() {
  \Drupal::logger('jcc_auto_archive')->info("awu hitting jcc_auto_archive_cron()");
  \Drupal::service('jcc_auto_archive.archiver_controller')->autoArchive_cron();
  \Drupal::logger('jcc_auto_archive')->info("awu called service's autoArchive_cron in jcc_auto_archive_cron()");
}


