<?php

/**
 * @file
 * Primary module hooks for 1CC Audio Stream module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function jcc_audio_stream_preprocess_node(&$variables) {
  // This is an unusual field/paragraph to attach the JS to, but it couldn't be
  // attached the normal way given how the accordion item paragraph is rendered
  // in twig.
  $variables['#attached']['library'][] = 'jcc_audio_stream/jcc_audio_stream';
}
