<?php

/**
 * @file
 * Contains jcc_blocks.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function jcc_node_edit_form_alter(&$form, &$form_state, $form_id) {
  // Node editing only customizations.
  if (str_starts_with($form_id, 'node_')) {
    $node = $form_state->getFormObject()->getEntity();

    // Suppress format options from tagline field.
    if (isset($form['field_tagline'])) {
      $form['field_tagline']['widget']['#after_build'][] = '_allowed_formats_remove_option';
    }

    switch ($form_id) {
      case 'node_news_edit_form':
        // Display hero image preference option to news feature only.
        $tid = $node->get('field_news_type')->getString();
        if (isset($tid) && $tid != "") {
          $newsType = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tid)->label();

          if ($newsType != 'Feature') {
            unset($form['field_second_image_as_hero']);
          }
        }
        else {
          unset($form['field_second_image_as_hero']);
        }
        break;
    }
  }
}

/**
 * Unset/Suppress formatting option elements.
 */
function _allowed_formats_remove_option($form_element, FormStateInterface $form_state) {
  if (isset($form_element[0]['format'])) {
    // All this stuff is needed to hide the help text.
    unset($form_element[0]['format']['guidelines']);
    unset($form_element[0]['format']['help']);
    unset($form_element[0]['format']['#type']);
    unset($form_element[0]['format']['#theme_wrappers']);
    $form_element[0]['format']['format']['#access'] = FALSE;
  }
  return $form_element;
}
