settings:
  library_url: ''
  css_url: ''
  crop_preview_image_style: crop_thumbnail
  crop_list: {  }
  crop_types_required: {  }
  warn_multiple_usages: false
  show_default_crop: true
  notify_apply: false
  notify_update: true
_core:
  default_config_hash: qS89jiXjXESbPzV9P9RZrynkHxqJg9rasPwxFPKSOCM
