remotevideoaccessibility:
  js:
    src/js/remotevideoaccessibility.js: {}
  dependencies:
    - core/jquery
    - core/drupal

image-styles:
  css:
    theme:
      src/css/image-styles.css: {}

granicus-events:
  css:
    theme:
      src/css/granicus-events.css: {}

search-filter-itc:
  css:
    theme:
      src/css/search-filter-itc.css: {}

surplus-materials:
  css:
    theme:
      src/css/surplus-materials.css: {}

jobs:
  css:
    theme:
      src/css/jobs.css: {}

jrn-directory-staff:
  css:
    theme:
      src/css/jrn-directory-staff.css: {}
