<?php

/**
 * @file
 * Primary module hooks for jcc_ical module.
 */

use Drupal\core\Url;
use Drupal\node\NodeInterface;

/**
 * Implements hook_node_links_alter().
 */
function jcc_ical_node_links_alter(array &$links, NodeInterface $entity, array &$context) {

  // Only add for configured content types.
  $config = \Drupal::config('jcc_ical.settings');
  $types = $config->get('types');

  if (!empty($types[$entity->getType()])) {
    // Generate link for iCal route.
    $url = Url::fromRoute('jcc_ical.content', ['node' => $entity->id()]);
    $attributes = [
      'class' => 'jcc-button--primary usa-button usa-button--primary',
      'aria-label' => 'Download event details for ' . $entity->getTitle(),
    ];

    $links['node']['#links']['ical'] = [
      'title' => t('Download Event'),
      'url' => $url,
      'attributes' => $attributes,
    ];
  }
}
