#!/usr/bin/env bash
#ddev-generated
## Description: Run Cypress Commands
## Usage: cypress-run [args]
## Example: "ddev cypress-run run --spec cypress/e2e/test.cy.js" or "ddev cypress-run run --url https://pr-123-build.example.org"
## RawArg: true
## Aliases: cy,cypress,cypress-run,cyr

set -e

# Make sure NVM works
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

cd ${DDEV_APPROOT}/tests/cypress
nvm use

# Parse --url flag from arguments, pass everything else to cypress
ENVIRONMENT="${DDEV_PRIMARY_URL}"
CYPRESS_ARGS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --url)
      ENVIRONMENT="$2"
      shift 2
      ;;
    *)
      CYPRESS_ARGS+=("$1")
      shift
      ;;
  esac
done

CYPRESS_BASE_URL="${ENVIRONMENT}" ./node_modules/.bin/cypress "${CYPRESS_ARGS[@]}"
