#!/usr/bin/env bash

## Description: Runs composer install and database refresh.
## Usage: db-rebuild
## Example: "ddev db-rebuild"
## Aliases: db:rebuild,rebuild,dbreb

#ddev-generated

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'
divider='===================================================\n'

# Install dependencies.
echo -e "\n${yellow} Composer install. ${NC}"
echo -e "${green}${divider}${NC}"
ddev composer install

# Database.
ddev db-refresh

echo "Clear cache"
ddev drush cr -y

echo "Update Drupal DB"
ddev drush updatedb -y

echo "Clear cache"
ddev drush cr -y

ddev cypress-users
