#!/usr/bin/env bash

## Description: Initializes NVM.
## Usage: project-nvm
## Example: "ddev project-nvm"
## Aliases: project:nvm

#ddev-generated

#-------------------------- Helper functions ------------------------------

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'
divider='===================================================\n'
construction='\xF0\x9F\x9A\xA7'

#-------------------------- Execution -------------------------------------

echo -e "\n${construction} ${yellow} Initializing NVM...${NC} ${construction}\n"
echo -e "${green}${divider}${NC}"
NVM_DIR="${HOME}/.nvm"
if [[ ! -d "$NVM_DIR" ]]; then
    echo -e "Installing NVM."
    echo -e "${green}${divider}${NC}"
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
    export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
fi
