theme: classy
defaults:
  sender: sendgrid_integration
  formatter: php_mail
_core:
  default_config_hash: EKcTdpJlgbuw6vwQA88pEhJM58Fp60vr73LtYPO4nEo
modules:
  sendgrid_integration:
    none:
      formatter: php_mail
      sender: sendgrid_integration
