label: 'Página de Diseño de bloques'
tips:
  block-layout:
    label: 'Diseño de bloque'
    body: 'Los bloques son envoltorios de contenido renderizados en una area o región de una página web que pueden ser mostrados en regiones (tales como pie o cabecera) en su página.'
  place-block:
    label: 'Colocar Bloques.'
    body: 'Cualquier bloque personalizado o contribuido se puede agregar a una región en particular haciendo clic en el botón Colocar bloque. También se puede crear un nuevo bloque haciendo clic en Colocar bloque.'
  block-region:
    label: 'Región de bloque'
    body: 'Asigne o cambie la región de un bloque haciendo click aquí. Aparecerá una lista desplegable con todas las regiones. Puedes poner el mismo bloque en varias regiones.'
  configure-block:
    label: 'Configurar bloque'
    body: 'Al hacer clic en "Configurar", puede seguir adelante y editar el contenido del bloque, editar la configuración de visibilidad e incluso cambiar la ubicación de donde se muestra en su tema.'
  custom-block-library:
    label: 'Librería personalizada de bloques'
    body: 'La pantalla de gestión de bloques tiene también otra pestaña en la parte superior que es utilizada para añadir bloques personalizados. El nombre de la pestaña es  "Librería de bloques personalizada". Esta pestaña proporciona un enlace para añadir bloques personalizados.'
