<?php

/**
 * @file
 * Contains jcc_twitter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function jcc_twitter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jcc_twitter module.
    case 'help.page.jcc_twitter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('JCC Twitter Post') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function jcc_twitter_node_insert(Node $node) {
  if ($node->bundle() == 'news') {

    $news_types = [];
    foreach ($node->field_news_type as $item) {
      if ($item->entity) {
        $news_types[$item->entity->id()] = $item->entity->label();
      }
    }
    if (!in_array('NewsLink', $news_types) &&
      $node->isPublished()
    ) {
      /* @var \Drupal\social_post_twitter\Plugin\Network\TwitterPostInterface $twitterPost */
      // Gets instance of Social Post Twitter.
      $twitterPost = \Drupal::service('plugin.network.manager')->createInstance('social_post_twitter');
      // Gets the Twitter entity storage.
      $twitterEntity = \Drupal::entityTypeManager()->getStorage('social_post_twitter_user');

      /* @var \Drupal\social_post_twitter\Entity\TwitterUserInterface[] $accounts */
      // Gets the Twitter accounts associated with the current user.
      $accounts = $twitterEntity->loadByProperties([
        'uid' => Drupal::currentUser()->id(),
      ]);

      $tweet = [
        'status' => $node->getTitle() . ' - ' . $node->url(),
      ];

      /*
       * Media files can be attached to the tweet.
       * $img_paths = [
       *   '/path/to/image.jpg',
       * ];
       *
       * $tweet['media_paths'] => $img_paths;
       */

      // Loop through each Twitter accounts.
      foreach ($accounts as $account) {
        $twitterPost->doPost($account->getAccessToken(), $account->getAccessTokenSecret(), $tweet);
      }
    }
  }
}
