enabled: false
settings:
  client_id: null
  client_secret: null
  authorization_endpoint_wa: 'https://example.com/oauth2/authorize'
  token_endpoint_wa: 'https://example.com/oauth2/token'
  userinfo_endpoint_wa: 'https://example.com/oauth2/UserInfo'
  group_mapping:
    mappings: null
_core:
  default_config_hash: 2OQBbEvK2JmsoWkIl2-Xceez9J-W6Ge0JOW_A8yrxPc
