<?php


use Drupal\Core\Database\Database;
/**
 * @file
 * Contains jcc_elevated_embeds module functionality.
 */

/**
 * Implements hook_theme().
 */
function jcc_elevated_embeds_theme($existing, $type, $theme, $path): array {
  return [
    'block__jcc_appellate_map' => [
      'variables' => [],
      'template' => 'block--jcc-appellate-map',
      'base hook' => 'block',
      'path' => $path . '/templates/appellate_map',
    ],
    'block__jcc_appellate_zcs' => [
      'variables' => [],
      'template' => 'block--jcc-appellate-zcs',
      'base hook' => 'block',
      'path' => $path . '/templates/appellate_zcs',
    ],
    'jcc_appellate_map' => [
      'path' => $path . '/templates/appellate_map',
      'variables' => [
        'legend' => [],
        'map_viewport' => [],
      ],
    ],
    'jcc_appellate_viewport' => [
      'path' => $path . '/templates/appellate_map',
      'variables' => [
        'district_info' => [],
        'map_src' => NULL,
      ],
    ],
    'jcc_appellate_district_legend' => [
      'path' => $path . '/templates/appellate_map',
      'variables' => [
        'district_info' => [],
      ],
    ],
    'block__jrn_directory' => [
      'variables' => [
        'jcc_court_options' => NULL,
      ],
      'template' => 'block--jrn-directory',
      'base hook' => 'block',
      'path' => $path . '/templates/jrn_directory',
    ],
  ];
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function jcc_elevated_embeds_entity_bundle_info_alter(array &$bundles) {
  // Help make it clearer that Content stream allows for embedding (blocks).
  if (jcc_custom_is_elevated_site()) {
    $bundles['paragraph']['content_stream']['label'] = "Content Stream/Embed";
  }
}

/**
 * Implements hook_block_field_block_field_selection_info_alter().
 */
function jcc_elevated_embeds_block_field_block_field_selection_info_alter(&$variables) {
  if (jcc_custom_is_elevated_site()) {
    // Change the blocks selection plugin.
    $variables['blocks']['id'] = "jcc_elevated_embeds_blocks";
    $variables['blocks']['label'] = t('JCC Elevated: Blocks');
    $variables['blocks']['class'] = "Drupal\jcc_elevated_embeds\Plugin\block_field\BlockFieldSelection\JccElevatedEmbedsBlocks";

    // Change the categories selection plugin.
    $variables['categories']['id'] = "jcc_elevated_embeds_blocks";
    $variables['categories']['label'] = t('JCC Elevated: Categories');
    $variables['categories']['class'] = "Drupal\jcc_elevated_embeds\Plugin\block_field\BlockFieldSelection\JccElevatedEmbedsBlocks";
  }
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function jcc_elevated_embeds_field_widget_entity_reference_paragraphs_form_alter(&$element, &$form_state, $context) {
  if ($element['#paragraph_type'] == 'content_stream') {
    if (isset($element['subform']['field_content_stream'])) {

      // Alter the field widget label.
      $element['subform']['field_content_stream']['widget']['#title'] = 'Content Stream/App/Block Embed';
      $element['subform']['field_content_stream']['widget'][0]['#title'] = 'Content Stream/App/Block Embed';

      // Add our own options.
      $options = jcc_elevated_embeds_jcc_allowed_content_stream_blocks_override(TRUE);
      $element['subform']['field_content_stream']['widget'][0]['plugin_id']['#options'] = $options;
    }
  }
}

/**
 * Find the available blocks that can be embedded in content_stream paragraphs.
 *
 * @param bool $flat
 *   Return a flat list of allowed blocks, keyed by plugin id.
 *
 * @return array
 *   Return an array of allowed blocks. Default is grouped by category/module.
 */
function jcc_elevated_embeds_jcc_allowed_content_stream_blocks_override($flat = FALSE): array {
  $options = [];
  $blockManager = \Drupal::service('plugin.manager.block');
  $contextRepository = \Drupal::service('context.repository');
  $definitions = $blockManager->getDefinitionsForContexts($contextRepository->getAvailableContexts());

  $all_options = [];
  foreach ($definitions as $plugin_id => $definition) {
    $all_options[$plugin_id] = [
      'label' => $definition['admin_label'],
      'group' => $definition['category'],
    ];
  }

  $set_overrides = \Drupal::state()->get('jcc_elevated_embeds.allowed_blocks') ?? [];
  $default_value = !empty($set_overrides) ? $set_overrides : array_keys($all_options);
  $override_values = array_combine($default_value, $default_value);

  if ($flat) {
    foreach ($override_values as $plugin_id => $name) {
      if (!is_numeric($plugin_id)) {
        $options[$plugin_id] = $all_options[$plugin_id]['label'];
      }
    }
  }
  else {
    foreach ($override_values as $plugin_id => $name) {
      if (!is_numeric($plugin_id)) {
        $options[$all_options[$plugin_id]['group']][$plugin_id] = $all_options[$plugin_id]['label'];
      }
    }
  }

  return $options;
}

/**
 * Implements hook_jcc_elevated_settings_alter().
 */
function jcc_elevated_embeds_jcc_elevated_settings_alter(&$settings) {
  // $settings['jcc_elevated.test'] = 'This is a test value';
}

/**
 * Implements hook_page_attachments().
 */
function jcc_elevated_embeds_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'jcc_elevated_embeds/form_redirect';
}

function jcc_elevated_embeds_form_views_exposed_form_alter(
  &$form,
  \Drupal\Core\Form\FormStateInterface $form_state,
  $form_id
) {
  $view = $form_state->get('view');
if ($view->id() === 'legislative_reports' || $view->current_display === 'block_1') {
    

  $category_names = ['Legislative Reports', 'Budget Allocations'];
$category_tids = [];

foreach ($category_names as $name) {
    $terms = \Drupal::entityTypeManager()
      ->getStorage('taxonomy_term')
      ->loadByProperties([
        'name' => $name,
        'vid' => 'media_file_category', // Replace with your vocabulary machine name
      ]);
   
    foreach ($terms as $term) {
        $category_tids[] = $term->id();
    }
}
 if (empty($category_tids)) {
    return; // No categories found, stop processing
  }

  
$media_ids = \Drupal::entityQuery('media')
  ->condition('status', 1)
  ->condition('field_category.target_id', $category_tids, 'IN')
  ->execute();

if (empty($media_ids)) {
  return;
}
$tag_tids = [];

$media_entities = \Drupal::entityTypeManager()
  ->getStorage('media')
  ->loadMultiple($media_ids);

foreach ($media_entities as $media) {
  if ($media->hasField('field_tags') && !$media->get('field_tags')->isEmpty()) {
    foreach ($media->get('field_tags')->getValue() as $item) {
      $tag_tids[] = $item['target_id'];
    }
  }
}

$tag_tids = array_unique($tag_tids);

if (empty($tag_tids)) {
  return;
}
$options = [];
$terms = \Drupal::entityTypeManager()
  ->getStorage('taxonomy_term')
  ->loadMultiple($tag_tids);

foreach ($terms as $term) {
  $options[$term->id()] = $term->label();
}
$form['field_tags_target_id']['#options'] = [
  'All' => t('- Any -'),
] + $options;
$form['field_tags_target_id']['#validated'] = TRUE;

}
}

