#uuid: c8412f69-8e49-4060-a235-7244f71ab1cd
langcode: en
status: true
dependencies: {  }
id: location_primary_section
class: null
field_plugin_method: null
cck_plugin_method: null
migration_tags:
  - jrn
  - location_primary
  - section
migration_group: jrn_location
label: 'JRN Location :Import Section'
source:
  plugin: csv
  path: 'public://serranus_addr_csv_sample.txt'
  header_row_count: 1
  ids:
    - ENTITY_ID
    #- LOC_NUM (there is going to be 1 section for each node)
  fields:
    -
      name: ENTITY_ID
      selector: ENTITY_ID
      label: Entity ID  
    -
      name: LOC_NUM
      selector: LOC_NUM
      label: Location Number 
process:
  pseudo_location:
    -
      plugin: migration_lookup 
      #plugin: migration_lookup_multiple
      migration: location_primary_paragraph
      source: 
        - ENTITY_ID
        - LOC_NUM
      no_stub: true
    -
      plugin: null_as_array
  field_components:
    -
      plugin: sub_process
      source:
        - '@pseudo_location'
      process:
        target_id:
          -
            plugin: skip_on_empty
            method: process
            message: 'Cannot import empty paragraph'
            source: '0'
        target_revision_id:
          -
            plugin: skip_on_empty
            method: process
            message: 'Cannot import empty paragraph'
            source: '1'
destination:
  plugin: 'entity_reference_revisions:paragraph'
  default_bundle: section
migration_dependencies:
  required:
    - location_primary_paragraph
