allowed_schemes:
  - private
template_scheme: public
shell_locale: en_US.UTF-8
remote_protocol: https
remote_endpoint: fillpdf.io/xmlrpc.php
_core:
  default_config_hash: IGXEOM4wHQhsKaCjAxgt-leFoP9014Gb7CQ-M2tSe8w
local_service_endpoint: 'https://jcc-fillpdf.azurewebsites.net'
backend: local_service
