features:
  node_user_picture: false
  comment_user_picture: false
  comment_user_verification: false
  favicon: false
logo:
  use_default: false
  path: 'public://logo.JPG'
favicon:
  use_default: true
email: webcontent@jud.ca.gov
facebook: ''
flickr: ''
linkedin: ''
rss: ''
twitter: ''
youtube: ''
hide_translation: 1
header_extended: 0
mega_menu: 0
footer_extended: 0
color_inverted: 0
footer_extended_message: ''
