theme: current
defaults:
  sender: php_mail
  formatter: php_mail
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  sendgrid_integration:
    none:
      formatter: sendgrid_integration
      sender: sendgrid_integration
