apikey: sendgrid_webservices
test_defaults:
  to: baptouille@gmail.com
  subject: 'Test Email from SendGrid Module'
  body:
    value: 'Test Message for SendGrid.'
    format: plain_text
  from_name: baptiste.niviere@gmail.com
  to_name: Baptest
  reply_to: ''
_core:
  default_config_hash: g4qz7cPnloXFwtnLYfIKI2VS0gf_UFOz_I2uQiiulC8
