name: 'California Judicial Branch Design System'
mail: baptiste.niviere@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: 39xtgXrOgWf5RNUvb1GEpd2NaWLBt_9KL4Ue2DG3NJk
uuid: 73a872b4-d715-47a1-b295-6c5567e4a803
mail_notification: ''
