_core:
  default_config_hash: AZ0iwlwLVSS0mPIsQvmIijaSe4gQMVBHi53gm-occJw
enable_log_deletion: false
timespan_limit: 30
batch_size: 50
disable_db_logs: false
log_cli: false
format: 'ELT [[event-log:type]] [[event-log:ref_char]] [[event-log:operation]] ON [[event-log:path]] BY [user:[event-log:user:uid]:[event-log:user:name]:[event-log:user:roles:join:,]] [[event-log:description]]'
output_type: watchdog
