#uuid: 660806e3-4489-4ed1-99b4-7cdcc13cf320
langcode: en
status: true
dependencies: {  }
id: itc_files_path_redirect
class: null
field_plugin_method: null
cck_plugin_method: null
migration_tags:
  - courts
  - itc
  - file
  - redirect
migration_group: courts
label: 'ITC: Import Path Redirects'
source:
  plugin: url
  data_fetcher_plugin: http
  data_parser_plugin: google_sheets
  urls: ''
  item_selector: entry
  fields:
    -
      name: id
      label: 'Unique ID'
      selector: url
    -
      name: url
      label: Url
      selector: url
  ids:
    id:
      type: string
  constants:
    uri_prefix: 'internal:'
    document_path: /system/files/
    status_code: 301
process:
  pseudo_base_path:
    plugin: public_files_dir
  pseudo_destination_filename:
    -
      plugin: path_from_url
      source: url
    -
      plugin: callback
      callable: basename
    -
      plugin: callback
      callable: urldecode
    -
      plugin: skip_on_empty
      method: process
      message: 'Cannot import empty image filename.'
  uid:
    plugin: default_value
    default_value: 1
  redirect_source/path:
    -
      plugin: callback
      callable: urldecode
      source: url
    -
      plugin: path_from_url
    -
      plugin: substr
      start: 1
  redirect_source/query: {  }
  redirect_redirect/uri:
    plugin: concat
    source:
      - constants/uri_prefix
      - constants/document_path
      - '@pseudo_destination_filename'
  status_code: constants/status_code
  language:
    plugin: default_value
    source: language
    default_value: en
destination:
  plugin: 'entity:redirect'
migration_dependencies:
  required: {}
  optional:
    - itc_files
