#uuid: f280d080-c3ea-4c78-a48c-9a7b754e7012
langcode: en
status: true
dependencies: {  }
id: facilities_forms_media
class: null
field_plugin_method: null
cck_plugin_method: null
migration_tags:
  - facilities
  - forms
  - media
migration_group: courts
label: 'Facilities: Import media'
source:
  plugin: url
  data_fetcher_plugin: http
  data_parser_plugin: google_sheets
  urls: 'https://sheets.googleapis.com/v4/spreadsheets/1iw2IqLI9Sn-XIPVKoq3WX0sVerkFChX9SYCxp8Mckmo/values/sheet3?alt=json&key=AIzaSyAzdemHmR62jLqko8umkV0-sNS080BgOJw'
  #urls: 'https://docs.google.com/spreadsheets/d/1iw2IqLI9Sn-XIPVKoq3WX0sVerkFChX9SYCxp8Mckmo/edit#gid=571553925'
  #urls: 'https://raw.githubusercontent.com/JudicialCouncilOfCalifornia/scrape/main/results/google-dca-publication.json'
  item_selector: entry
  ids:
    id:
      type: string   
  fields:
    -
      name: id
      selector: id
      label: 'Unique Identifier'
    -
      name: title
      selector: title
      label: Title   
    -
      name: file_type
      label: 'File type'
      selector: type    
process:
  pseudo_encoded_title:
    plugin: callback
    callable: htmlspecialchars_decode
    source: title
  pseudo_destination_filename:
    -
      plugin: path_from_url
      source: url
      #remove_extension: true
    -
      plugin: callback
      callable: basename
    -
      plugin: callback
      callable: urldecode    
    -
      plugin: skip_on_empty
      method: process
      message: 'Cannot import empty image filename.'
  name: '@pseudo_destination_filename'
  field_media_file/target_id:
    #needed for facilities node (field_media_file_multiple?)
    #-
    #  plugin: explode
    #  source: id
    #  delimiter: ','
    -
      plugin: migration_lookup
      migration: facilities_forms_file
      source: id
    -
      plugin: skip_on_empty
      method: process
      message: 'Cannot import empty filename.'
  field_media_file/description: '@pseudo_encoded_title'
  #field_category: 
  #  -
  #    plugin: explode
  #    source: media_type
  #    delimiter: ','
  #  -
  #    plugin: entity_generate
  #    entity_type: taxonomy_term
  #    bundle_key: vid
  #    bundle: media_file_category
  #    value_key: name
  #    ignore_case: true
  uid:
    plugin: default_value
    default_value: 1  
destination:
  plugin: 'entity:media'
  default_bundle: file
migration_dependencies:
  required:
    - facilities_forms_file