#uuid: 0c301833-dde5-4a43-9589-68e8b2e2bb2d
langcode: en
status: true
dependencies: {  }
id: facilities_images
class: null
field_plugin_method: null
cck_plugin_method: null
migration_tags:
  - courts
  - forms
  - images
migration_group: courts
label: 'Facilities: Import images'
source:
  plugin: url
  data_fetcher_plugin: http
  data_parser_plugin: google_sheets
  urls: 'https://sheets.googleapis.com/v4/spreadsheets/1iw2IqLI9Sn-XIPVKoq3WX0sVerkFChX9SYCxp8Mckmo/values/sheet2?alt=json&key=AIzaSyAzdemHmR62jLqko8umkV0-sNS080BgOJw'
  item_selector: entry
  ids:
    id:
      type: string
  fields:
    -
      name: id
      selector: url
      label: 'Unique Identifier'
    -
      name: title
      selector: title
      label: Title
    -
      name: url
      selector: url
      label: URL
process:
  pseudo_encoded_title:
    plugin: callback
    callable: htmlspecialchars_decode
    source: title
  pseudo_destination_filename:
    -
      plugin: path_from_url
      source: url
    -
      plugin: callback
      callable: basename
    -
      plugin: callback
      callable: urldecode
    -
      plugin: str_replace
      search: ' '
      replace: '-'
    -
      plugin: callback
      callable: strtolower
    -
      plugin: skip_on_empty
      method: process
      message: 'Cannot import empty image filename.'
  name: '@pseudo_destination_filename'
  field_media_image:
      -
        plugin: explode
        delimiter: ','
        source: url
      -
        plugin: callback
        callable: trim
      -
        plugin: migration_lookup
        migration: appellate_forms_file
  field_media_caption/value: '@pseudo_encoded_title'
  field_media_caption/format: caption
  uid:
    plugin: default_value
    default_value: 1
destination:
  plugin: 'entity:media'
  default_bundle: image
migration_dependencies:
  required:
    - facilities_forms_file
