#uuid: 32fd5c48-a7bf-4d7a-b529-7b2144ac58e5
langcode: en
status: true
dependencies: {  }
id: facilities_forms_file_path_redirect
class: null
field_plugin_method: null
cck_plugin_method: null
migration_tags:
  - facilities
  - forms
  - file
  - redirect
migration_group: courts
label: 'Facilities: Import Path Redirects'
source:
  plugin: url
  data_fetcher_plugin: http
  data_parser_plugin: google_sheets
  urls: 'https://sheets.googleapis.com/v4/spreadsheets/1iw2IqLI9Sn-XIPVKoq3WX0sVerkFChX9SYCxp8Mckmo/values/sheet3?alt=json&key=AIzaSyAzdemHmR62jLqko8umkV0-sNS080BgOJw'
  item_selector: entry
  fields:
    -
      name: id
      label: 'Unique ID'
      selector: url
    -
      name: url
      label: Url
      selector: url
  ids:
    id:
      type: string
  constants:
    uri_prefix: 'internal:'
    document_path: /system/files/
    status_code: 301
process:
  pseudo_base_path:
    plugin: public_files_dir
  pseudo_destination_filename:
    -
      plugin: path_from_url
      source: url
    -
      plugin: callback
      callable: basename
    -
      plugin: callback
      callable: urldecode
    -
      plugin: skip_on_empty
      method: process
      message: 'Cannot import empty image filename.'
  uid:
    plugin: default_value
    default_value: 1
  redirect_source/path:
    -
      plugin: callback
      callable: urldecode
      source: url
    -
      plugin: path_from_url
    -
      plugin: substr
      start: 1
  redirect_source/query: {  }
  redirect_redirect/uri:
    plugin: concat
    source:
      - constants/uri_prefix
      - constants/document_path
      - '@pseudo_destination_filename'
  status_code: constants/status_code
  language:
    plugin: default_value
    source: language
    default_value: en
destination:
  plugin: 'entity:redirect'
migration_dependencies:
  required:
    - facilities_forms_file
