#uuid: 049ddc09-5453-47c3-b02b-7f798fd9b813
langcode: en
status: true
dependencies: {  }
id: facilities
class: null
field_plugin_method: null
cck_plugin_method: null
migration_tags:
  - node
migration_group: courts
label: 'Facilities'
source:
  plugin: url
  data_fetcher_plugin: http
  data_parser_plugin: google_sheets
  urls: 'https://sheets.googleapis.com/v4/spreadsheets/1iw2IqLI9Sn-XIPVKoq3WX0sVerkFChX9SYCxp8Mckmo/values/sheet2?alt=json&key=AIzaSyAzdemHmR62jLqko8umkV0-sNS080BgOJw'
  item_selector: entry
  ids:
    id:
      type: string
  fields:
  #<<todo>>>      
process:  
  title: 'title' 
destination:
  plugin: 'entity:node'
  default_bundle: facilities
migration_dependencies:
  optional:
    - facilities_forms_media
    - appellate_images
