#uuid: 2781b17f-899e-4dd3-8d8f-ba351913d638
langcode: en
status: true
dependencies: {  }
id: facilities_forms_file_images
class: null
field_plugin_method: null
cck_plugin_method: null
migration_tags:
  - facilities
  - forms
  - file
migration_group: courts
label: 'Facilities: Import facility files images'
source:
  plugin: url
  data_fetcher_plugin: http
  data_parser_plugin: google_sheets  
  urls: 'https://sheets.googleapis.com/v4/spreadsheets/1iw2IqLI9Sn-XIPVKoq3WX0sVerkFChX9SYCxp8Mckmo/values/sheet2?alt=json&key=AIzaSyAzdemHmR62jLqko8umkV0-sNS080BgOJw'
  item_selector: entry
  ids:
    id:
      type: string
  fields:
    -
      name: id
      selector: url
      label: 'Unique Identifier'
    -
      name: url
      selector: url
      label: 'Attachment file url'
  constants:
    DRUPAL_FILE_DIRECTORY: 'public://facilities/'
process:
  pseudo_decoded_url:
    plugin: callback
    callable: urldecode
    source: url
  pseudo_destination_filename:
    -
      plugin: path_from_url
      source: url
    -
      plugin: callback
      callable: basename
    -
      plugin: callback
      callable: urldecode
    -
      plugin: str_replace
      search: ' '
      replace: '-'
    -
      plugin: callback
      callable: strtolower
    -
      plugin: skip_on_empty
      method: process
      message: 'Could not create file from URL.'
  pseudo_destination_path:
    -
      plugin: concat
      source:
        - constants/DRUPAL_FILE_DIRECTORY
        - '@pseudo_destination_filename'
  uri:
    -
      plugin: skip_on_empty
      method: process
      source: url
    -
      plugin: file_copy
      source:
        - '@pseudo_decoded_url'
        - '@pseudo_destination_path'
      file_exists: rename
      move: false
destination:
  plugin: 'entity:file'
migration_dependencies: null
