#uuid: 14567de7-e195-4ba6-a644-8242cc9abbfa
langcode: en
status: true
dependencies: {  }
id: itc_files
class: null
field_plugin_method: null
cck_plugin_method: null
migration_tags:
  - courts
  - itc
  - file
migration_group: courts
label: 'ITC: Import files'
source:
  plugin: url
  data_fetcher_plugin: http
  data_parser_plugin: google_sheets
  urls: ''
  item_selector: entry
  ids:
    id:
      type: string
  fields:
    -
      name: id
      selector: id
      label: 'Unique Identifier'
    -
      name: url
      selector: id
      label: 'Attachment file url'
  constants:
    DRUPAL_FILE_DIRECTORY: 'public://itc/'
process:
  pseudo_decoded_url:
    plugin: callback
    callable: urldecode
    source: url
  pseudo_destination_filename:
    -
      plugin: path_from_url
      source: url
    -
      plugin: callback
      callable: basename
    -
      plugin: callback
      callable: urldecode
    -
      plugin: str_replace
      search: ' '
      replace: '-'
    -
      plugin: callback
      callable: strtolower
    -
      plugin: skip_on_empty
      method: process
      message: 'Could not create file from URL.'
  pseudo_destination_path:
    -
      plugin: concat
      source:
        - constants/DRUPAL_FILE_DIRECTORY
        - '@pseudo_destination_filename'
  uri:
    -
      plugin: skip_on_empty
      method: process
      source: url
    -
      plugin: file_copy
      source:
        - '@pseudo_decoded_url'
        - '@pseudo_destination_path'
      file_exists: rename
      move: false
destination:
  plugin: 'entity:file'
migration_dependencies: null
