#uuid: 5cc3b8e8-503c-4245-98d2-6da8bc8d682c
langcode: en
status: true
dependencies: {  }
id: itc_node
class: null
field_plugin_method: null
cck_plugin_method: null
migration_tags:
  - courts
  - node
  - itc
migration_group: courts
label: 'ITC: Import nodes'
source:
  plugin: url
  data_fetcher_plugin: http
  data_parser_plugin: google_sheets
  urls: ''
  item_selector: entry
  ids:
    id_href:
      type: string
    field_category:
      type: string  
  fields:
    -
      name: id_href
      selector: id_href
      label: Id
    -
      name: title
      selector: title
      label: Title    
    -
      name: field_category
      selector: field_category
      label: 'Category'
    -
      name: field_itc_number
      selector: field_itc_number
      label: 'ITC Number' 
    -
      name: field_status
      selector: field_status
      label: 'Status'   
    -
      name: body
      selector: body
      label: Body
    - 
      name: field_file
      selector: field_file
      label: File    
process:
  uid:
    plugin: default_value
    default_value: 1
  title:
    -
      plugin: get
      source: title
    -
      plugin: default_value
      default_value: TITLE
  field_itc_number: field_itc_number
  field_category:
    -
      plugin: skip_on_empty
      method: process
      source: field_category
    -
      plugin: entity_generate
      entity_type: taxonomy_term
      bundle_key: vid
      bundle: category
      value_key: name
      ignore_case: true  
  field_status:
    -
      plugin: get
      source: field_status
    -  
      plugin: default_value
      default_value: Closed      
    -
      plugin: skip_on_empty
      method: process
  body/value:
    plugin: get
    source: body
  body/format:
    plugin: default_value
    default_value: body
  field_file:  
    -
      plugin: skip_on_empty
      method: process
      source: id_href   
    -
      plugin: migration_lookup
      migration: itc_media 
      source: id_href 
      #-
    #  plugin: skip_on_empty
    #  method: process
    #  source: id_href
    #-
    #  plugin: callback
    #  callable: trim  
    #- plugin: media_replace_file_link
    #  source: body_text
    #- plugin: prefix_relative_links
  #body/format:
    #plugin: default_value
    #default_value: body      
  #body/value:
  #  - plugin: sub_process
  #    source: body_1
  #    process:
  #      extracted_description:
  #        plugin: extract
  #        source: itc_description
  #  - plugin: callback
  #    callable: jcc_elevated_custom_implode_array
  #    arguments:
  #      - '@extracted_description'
  #      - ' ' 
destination:
  plugin: 'entity:node'
  default_bundle: invitations_to_comment
migration_dependencies: null
  #optional:
  #  - itc_media    
