# uuid: e30520b5-dac5-4b6a-b285-db7055472aac
# langcode: en
# status: true
# dependencies:
#   config:
#     - node.type.facilities
#   module:
#     - node
#     - options
#     - user
# id: facilities
# label: facilities
# module: views
# description: ''
# tag: ''
# base_table: node_field_data
# base_field: nid
# display:
#   default:
#     id: default
#     display_title: Default
#     display_plugin: default
#     position: 0
#     display_options:
#       title: facilities
#       fields:
#         title:
#           id: title
#           table: node_field_data
#           field: title
#           relationship: none
#           group_type: group
#           admin_label: ''
#           plugin_id: field
#           label: ''
#           exclude: false
#           alter:
#             alter_text: false
#             text: ''
#             make_link: false
#             path: ''
#             absolute: false
#             external: false
#             replace_spaces: false
#             path_case: none
#             trim_whitespace: false
#             alt: ''
#             rel: ''
#             link_class: ''
#             prefix: ''
#             suffix: ''
#             target: ''
#             nl2br: false
#             max_length: 0
#             word_boundary: true
#             ellipsis: true
#             more_link: false
#             more_link_text: ''
#             more_link_path: ''
#             strip_tags: false
#             trim: false
#             preserve_tags: ''
#             html: false
#           element_type: ''
#           element_class: ''
#           element_label_type: ''
#           element_label_class: ''
#           element_label_colon: true
#           element_wrapper_type: ''
#           element_wrapper_class: ''
#           element_default_classes: true
#           empty: ''
#           hide_empty: false
#           empty_zero: false
#           hide_alter_empty: true
#           click_sort_column: value
#           type: string
#           settings:
#             link_to_entity: true
#           group_column: value
#           group_columns: {  }
#           group_rows: true
#           delta_limit: 0
#           delta_offset: 0
#           delta_reversed: false
#           delta_first_last: false
#           multi_type: separator
#           separator: ', '
#           field_api_classes: false
#       pager:
#         type: some
#         options:
#           offset: 0
#           items_per_page: 5
#       exposed_form:
#         type: basic
#         options:
#           submit_button: Apply
#           reset_button: false
#           reset_button_label: Reset
#           exposed_sorts_label: 'Sort by'
#           expose_sort_order: true
#           sort_asc_label: Asc
#           sort_desc_label: Desc
#       access:
#         type: perm
#         options:
#           perm: 'access content'
#       cache:
#         type: tag
#         options: {  }
#       empty: {  }
#       sorts:
#         created:
#           id: created
#           table: node_field_data
#           field: created
#           relationship: none
#           group_type: group
#           admin_label: ''
#           entity_type: node
#           entity_field: created
#           plugin_id: date
#           order: DESC
#           expose:
#             label: ''
#             field_identifier: ''
#           exposed: false
#           granularity: second
#       arguments: {  }
#       filters:
#         status:
#           id: status
#           table: node_field_data
#           field: status
#           entity_type: node
#           entity_field: status
#           plugin_id: boolean
#           value: '1'
#           group: 1
#           expose:
#             operator: ''
#             operator_limit_selection: false
#             operator_list: {  }
#         type:
#           id: type
#           table: node_field_data
#           field: type
#           entity_type: node
#           entity_field: type
#           plugin_id: bundle
#           value:
#             facilities: facilities
#           expose:
#             operator_limit_selection: false
#             operator_list: {  }
#         field_project_status_value:
#           id: field_project_status_value
#           table: node__field_project_status
#           field: field_project_status_value
#           relationship: none
#           group_type: group
#           admin_label: ''
#           plugin_id: list_field
#           operator: or
#           value:
#             inprogress: inprogress
#             completed: completed
#           group: 1
#           exposed: true
#           expose:
#             operator_id: field_project_status_value_op
#             label: 'Project Status'
#             description: ''
#             use_operator: false
#             operator: field_project_status_value_op
#             operator_limit_selection: false
#             operator_list: {  }
#             identifier: field_project_status_value
#             required: false
#             remember: false
#             multiple: false
#             remember_roles:
#               authenticated: authenticated
#               author: '0'
#               legal_files: '0'
#               editor: '0'
#               manager: '0'
#               contributor: '0'
#               translator: '0'
#               administrator: '0'
#               anonymous: '0'
#               tentative_rulings_editor: '0'
#               messaging_manager: '0'
#               facilities: '0'
#             reduce: false
#           is_grouped: false
#           group_info:
#             label: ''
#             description: ''
#             identifier: ''
#             optional: true
#             widget: select
#             multiple: false
#             remember: false
#             default_group: All
#             default_group_multiple: {  }
#             group_items: {  }
#           reduce_duplicates: false
#       style:
#         type: default
#       row:
#         type: fields
#       query:
#         type: views_query
#         options:
#           query_comment: ''
#           disable_sql_rewrite: false
#           distinct: false
#           replica: false
#           query_tags: {  }
#       relationships: {  }
#       header: {  }
#       footer: {  }
#       display_extenders: {  }
#     cache_metadata:
#       max-age: -1
#       contexts:
#         - 'languages:language_content'
#         - 'languages:language_interface'
#         - url
#         - 'user.node_grants:view'
#         - user.permissions
#       tags: {  }
#   block_1:
#     id: block_1
#     display_title: Block
#     display_plugin: block
#     position: 1
#     display_options:
#       exposed_block: false
#       display_extenders: {  }
#     cache_metadata:
#       max-age: -1
#       contexts:
#         - 'languages:language_content'
#         - 'languages:language_interface'
#         - url
#         - 'user.node_grants:view'
#         - user.permissions
#       tags: {  }
