display:
  embed_administer:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Action
  embed_manage:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Action
