display:
  default:
    display_options:
      fields:
        media_bulk_form:
          action_title: Acción
  page:
    display_title: NewsLinks
    display_options:
      fields:
        media_bulk_form:
          action_title: Acción
