display:
  default:
    display_options:
      fields:
        comment_bulk_form:
          action_title: Acción
  page_unapproved:
    display_options:
      fields:
        comment_bulk_form:
          action_title: Acción
