display:
  default:
    display_options:
      fields:
        media_bulk_form:
          action_title: Action
  page:
    display_title: Page
    display_options:
      fields:
        media_bulk_form:
          action_title: Action
