field.formatter.settings.linkit_field_linkit:
  type: mapping
  label: Linkit formatter settings
  mapping:
    foo:
      type: string
      label: Foo

field.widget.settings.linkit_field_linkit:
  type: mapping
  label: Linkit widget settings
  mapping:
    foo:
      type: string
      label: Foo
