country:
  default: US
first_day: 0
timezone:
  default: America/Los_Angeles
  user:
    configurable: true
    warn: false
    default: 0
_core:
  default_config_hash: JTZVMH3FT3rJ22CFjUf6J4Rmz9PxM6El9VDSwmBiv4E
