_core:
  default_config_hash: y5Xg-FUIU8W1dPEQKblOm3AsAJ7PCh-MFBJ-4Dv9TCE
hash_key: auHash
duration: 172800
cleanup_expired_tokens: true
cleanup_expired_tokens_period: '-2 weeks'
modify_http_headers: {  }
