ignored_config_entities:
  - openid_connect.settings.windows_aad
  - geocoder.geocoder_provider.bingmaps
  - system.site
  - extlink.settings
  - block.block.jccglossifypathexclusion
  - block.block.jccbooknavigationblock
  - jcc_components.settings.logo
  - jcc_components.settings.facebook
  - jcc_components.settings.twitter
  - jcc_components.settings.youtube
  - jcc_components.settings.scheme
  - jcc_components.settings.email
  - jcc_components.settings.flickr
  - jcc_components.settings.linkedin
  - jcc_components.settings.rss
  - jcc_components.settings.header_footer_variant
  - jcc_components.settings.site_name_first
  - jcc_components.settings.site_name_second
  - jcc_components.settings.hat_shoe_title
  - jcc_components.settings.hat_shoe_url
  - jcc_components.settings.hat_shoe_text
_core:
  default_config_hash: 0bdREz-FwypiNhaqHGTyrC1jrjwR1-Pj7c-1ijJu5yY
