_core:
  default_config_hash: VYqWQ-gT-WO-gIqvz4PmibMjb7zVLz5RO-k-zw1Jjgw
ignored_config_entities:
  - openid_connect.settings.windows_aad
  - geocoder.geocoder_provider.bingmaps
  - 'google_tag.container.*'
  - google_tag.settings
  - system.site
  - block.block.jccglossifypathexclusion
  - block.block.jccbooknavigationblock
  - jcc_components.settings
  - recaptcha.settings
  - 'key.key.*'
  - 'webform.webform.*'
  - protected_pages.settings
  - 'xmlsitemap.xmlsitemap.*'
  - 'xlsx.xlsx.*'
