_core:
  default_config_hash: UeLeXCdQUQqf-eez44suCE7EfX1N209uE1rHc7UAit0
ignored_config_entities:
  - openid_connect.settings
  - 'openid_connect.settings.*'
  - openid_connect.settings.windows_aad
  - geocoder.geocoder_provider.bingmaps
  - 'google_tag.container.*'
  - google_tag.settings
  - system.site
  - block.block.jccglossifypathexclusion
  - block.block.jccbooknavigationblock
  - jcc_components.settings
  - recaptcha.settings
  - 'key.key.*'
  - 'webform.webform.*'
  - protected_pages.settings
  - sitemap.settings
  - 'xmlsitemap.xmlsitemap.*'
  - 'xlsx.xlsx.*'
