ignored_config_entities:
  - 'jcc_*.settings'
  - openid_connect.settings.windows_aad
  - geocoder.geocoder_provider.bingmaps
  - system.site
  - extlink.settings
  - block.block.jccglossifypathexclusion
  - block.block.jccbooknavigationblock
_core:
  default_config_hash: 8gFTQUc9PO3Y0wRRx9CugpXDwJnVjlwKDJLQQDsOBuU
