status: true
dependencies:
  config:
    - field.field.node.judge.body
    - field.field.node.judge.field_address
    - field.field.node.judge.field_custom_link
    - field.field.node.judge.field_date
    - field.field.node.judge.field_department
    - field.field.node.judge.field_division
    - field.field.node.judge.field_job_title
    - field.field.node.judge.field_location
    - field.field.node.judge.field_media
    - field.field.node.judge.field_media_file_multiple
    - field.field.node.judge.field_person_type
    - field.field.node.judge.field_retirement_date
    - field.field.node.judge.field_tags
    - node.type.judge
  module:
    - address
    - datetime
    - text
    - user
id: node.judge.default
targetEntityType: node
bundle: judge
mode: default
content:
  body:
    type: text_default
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 6
    region: content
  field_address:
    type: address_default
    label: hidden
    settings: {  }
    third_party_settings: {  }
    weight: 2
    region: content
  field_date:
    type: datetime_default
    label: above
    settings:
      timezone_override: ''
      format_type: medium
    third_party_settings: {  }
    weight: 4
    region: content
  field_department:
    type: entity_reference_label
    label: hidden
    settings:
      link: false
    third_party_settings: {  }
    weight: 1
    region: content
  field_division:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 3
    region: content
  field_job_title:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 10
    region: content
  field_location:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 11
    region: content
  field_media:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 8
    region: content
  field_media_file_multiple:
    type: entity_reference_entity_view
    label: above
    settings:
      view_mode: default
      link: false
    third_party_settings: {  }
    weight: 12
    region: content
  field_person_type:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 7
    region: content
  field_retirement_date:
    type: datetime_default
    label: above
    settings:
      timezone_override: ''
      format_type: medium
    third_party_settings: {  }
    weight: 9
    region: content
  field_tags:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 13
    region: content
  links:
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  entity_print_view_epub: true
  entity_print_view_pdf: true
  entity_print_view_word_docx: true
  field_custom_link: true
  langcode: true
  search_api_excerpt: true
