_core:
  default_config_hash: R-uga8FqoK_wvvUNZ9C-25fkyC1NLyGnxdNOInbuFe4
applies_admin_routes: true
include_invalid_paths: true
excluded_paths: ''
replaced_titles: ''
custom_paths: ''
include_home_segment: false
home_segment_title: Home
home_segment_keep: false
include_title_segment: true
title_from_page_when_available: true
title_segment_as_link: false
segments_separator: null
use_menu_title_as_fallback: true
use_page_title_as_menu_title_fallback: false
remove_repeated_segments: true
language_path_prefix_as_segment: false
absolute_paths: false
hide_single_home_item: true
term_hierarchy: false
use_site_title: false
add_structured_data_json_ld: 0
capitalizator_mode: none
capitalizator_ignored_words: ''
capitalizator_forced_words: ''
capitalizator_forced_words_case_sensitivity: 0
capitalizator_forced_words_first_letter: 0
