_core:
  default_config_hash: FKNLyMXSgJfGtl7OacVY5DhH4QyGdzQ-1iJ3IoDSpo8
local_task_enabled_entity_types:
  - media
  - node
  - taxonomy_term
  - paragraphs_library_item
track_enabled_source_entity_types:
  - node
  - media
  - paragraph
  - taxonomy_term
track_enabled_target_entity_types:
  - node
  - media
  - paragraph
  - taxonomy_term
track_enabled_plugins:
  - entity_reference
  - block_field
  - dynamic_entity_reference
  - layout_builder
  - link
  - linkit
  - entity_embed
  - media_embed
  - html_link
track_enabled_base_fields: false
site_domains: {  }
edit_warning_message_entity_types:
  - paragraphs_library_item
delete_warning_message_entity_types:
  - paragraphs_library_item
usage_controller_items_per_page: 25
