_core:
  default_config_hash: ztJk_Bb6uvKGwk1E3H6FGD6em6JkMR2tAMokaE4GBfU
description:
  type: textfield
  length: 128
icon:
  directory: core/modules/file/icons
make_unused_managed_files_temporary: false
