_core:
  default_config_hash: c_BztFaDwUmjevfzGy-VnQgDHyNIA9AoZ-vApEwnTb4
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  use_default: true
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: light_blue
preset_focus_color: gin
enable_darkmode: '0'
classic_toolbar: classic
secondary_toolbar_frontend: false
high_contrast_mode: false
accent_color: ''
focus_color: ''
show_description_toggle: false
show_user_theme_settings: true
icon_default: true
icon_path: ''
icon_upload: ''
