_core:
  default_config_hash: 2QxKdCjt5I2uXGX3t6oPolNHl1JwOVbH-_1LiaOyAt8
protect_all_forms: true
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: false
element_name: descriptive-language
time_limit: 0
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_feedback_form: false
  contact_message_personal_form: false
  node_alert_form: false
  node_document_form: false
  node_importer_form: false
  node_landing_page_form: false
  node_location_form: false
  node_news_form: false
  node_subpage_form: false
