_core:
  default_config_hash: ReVi05NGALl2PPQDjnTEUi_ktL86T8iy0f9vH4uhcZQ
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
  domains:
    en: ''
    es: ''
selected_langcode: site_default
