_core:
  default_config_hash: ScXVCYgsLNeEVs6Qmq55O6-SqZZRSd6FMP-UYFkKXnY
theme: classy
defaults:
  sender: sendgrid_integration
  formatter: mime_mail
modules:
  sendgrid_integration:
    none:
      sender: sendgrid_integration
      formatter: mime_mail
