_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: classy
defaults:
  sender: sendgrid_integration
  formatter: mime_mail
modules:
  sendgrid_integration:
    none:
      sender: sendgrid_integration
      formatter: mime_mail
