_core:
  default_config_hash: 82poIXbhSkIO2JPshdZTWjn3J5EQO0NfKaVvi3UQzy0
format: body
name: 'Superior Court of California | County of Inyo'
mail: no-reply@courtinfo.ca.gov
linkonly: false
textonly: false
sitestyle: true
simple_address: false
preserve_class: false
advanced:
  incoming: false
  key: Pfr1wJPaKG2rAltu7qeJxUgcy44_tD_akAg-UfgWkCA
