grants:
  view: 0
  edit: 1
  delete: 0
priority: 0
preserve: 1
_core:
  default_config_hash: 27_h4321UycP9rVZ52HRLii3ePLqqGiJVuTBcW-CrsI
alert:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  legal_files:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  editor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  manager:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  translator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  contributor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
document:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  legal_files:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  editor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  manager:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  translator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  contributor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
importer:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  legal_files:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  editor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  manager:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  translator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  contributor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
landing_page:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  contributor:
    grant_update: '1'
    grant_view: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  legal_files:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  editor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  manager:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  translator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
location:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  legal_files:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  editor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  manager:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  translator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  contributor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
news:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  legal_files:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  editor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  manager:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  translator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  contributor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
subpage:
  anonymous:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  authenticated:
    grant_view: '1'
    grant_update: 0
    grant_delete: 0
  contributor:
    grant_update: '1'
    grant_view: 0
    grant_delete: 0
  author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  legal_files:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  editor:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  manager:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  translator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
role_alias:
  author:
    alias: Author
    weight: '0'
    name: Author
    allow: 0
  legal_files:
    alias: 'Legal & Files'
    weight: '0'
    name: 'Legal & Files'
    allow: 0
  editor:
    alias: Editor
    weight: '0'
    name: Editor
    allow: 0
  manager:
    alias: Manager
    weight: '0'
    name: Manager
    allow: 0
  translator:
    alias: Translator
    weight: '0'
    name: Translator
    allow: 0
  administrator:
    alias: Administrator
    weight: '0'
    name: Administrator
    allow: 0
  anonymous:
    alias: 'Anonymous user'
    weight: '0'
    name: 'Anonymous user'
    allow: 0
  authenticated:
    alias: 'Authenticated user'
    weight: '0'
    name: 'Authenticated user'
    allow: 0
  contributor:
    alias: Contributor
    weight: '0'
    name: Contributor
    allow: 0
role_map:
  author: 1
  legal_files: 2
  editor: 3
  manager: 4
  translator: 5
  administrator: 6
  anonymous: 7
  authenticated: 8
  contributor: 9
allowed_types:
  alert: 0
  document: 0
  importer: 0
  landing_page: 0
  location: 0
  news: 0
  subpage: 1
