always_save_userinfo: true
connect_existing_users: true
override_registration_settings: false
userinfo_mappings:
  timezone: zoneinfo
  metatag: 0
  path: 0
  user_picture: 0
_core:
  default_config_hash: 1lY8x1-yf5yJibE8MM1ZAGTtINCLktDL3jZt1kkCtCA
