auto_redirect: true
default_status_code: 301
passthrough_querystring: true
warning: false
ignore_admin_path: false
access_check: false
route_normalizer_enabled: true
_core:
  default_config_hash: mIwFOHQ2WanLis-8IYjeo2XPeU7ewDDQaL8yQwxLmGY
