_core:
  default_config_hash: IvqSsKmviMU7pCloALfQo4HLAdg4nK3E7tD0rIkQF8Y
allow_date_only: true
date_format: 'Y-m-d H:i:s'
date_letters: djmnFMyY
date_only_format: Y-m-d
default_expand_fieldset: when_required
default_fields_display_mode: vertical_tab
default_publish_enable: false
default_publish_past_date: error
default_publish_past_date_created: false
default_publish_required: false
default_publish_revision: false
default_publish_touch: false
default_time: '00:00:00'
default_unpublish_enable: false
default_unpublish_required: false
default_unpublish_revision: false
lightweight_cron_access_key: 7fb5300f86a7910fa641
log: true
time_letters: hHgGisaA
time_only_format: 'H:i:s'
