_core:
  default_config_hash: TOg4FNuqfbJzEEf6FrX3a_GZ9ESqP_HsegjSE9xHfWE
first_day: 0
country:
  default: US
timezone:
  default: America/Los_Angeles
  user:
    configurable: true
    default: 0
    warn: false
