_core:
  default_config_hash: WSDg24hgMQoWOzggnDJv_k_mDxeE2Z7fI_Vnix6QxbE
first_day: 0
country:
  default: US
timezone:
  default: America/Los_Angeles
  user:
    configurable: false
    default: 0
    warn: false
