_core:
  default_config_hash: NVIGpBy3cv4vaOIAu_IzHemtuwccRRuu_PVvhL1BEzg
check:
  disabled_extensions: false
  interval_days: 1
fetch:
  url: ''
  max_attempts: 2
  timeout: 30
notification:
  emails:
    - jcc@example.com
  threshold: all
