_core:
  default_config_hash: pgeiOCRuBXThGpfqeK-af2gy2lbLmzOH6un5F0OQ_ds
check:
  disabled_extensions: false
  interval_days: 1
fetch:
  url: ''
  max_attempts: 2
  timeout: 30
notification:
  emails:
    - jcc@example.com
  threshold: all
