module:
  jcc_components_profile: 0
  path_alias: 0
  protected_pages: 0
  system: 0
  user: 0
theme: {  }
profile: jcc_components_profile
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
