module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  book: 0
  breakpoint: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  color: 0
  comment: 0
  components: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  encrypt: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geolocation: 0
  geolocation_leaflet: 0
  ga_login: 0
  honeypot: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jcc_featured_links: 0
  jcc_ical: 0
  key: 0
  link: 0
  linkit: 0
  login_emailusername: 0
  media: 0
  media_library: 0
  menu_item_extras: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  module_filter: 0
  node: 0
  office_hours: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rdf: 0
  real_aes: 0
  redirect: 0
  responsive_image: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  search: 0
  svg_image: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  tfa: 0
  token: 0
  toolbar: 0
  user: 0
  views_ui: 0
  workflows: 0
  extlink: 1
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  jcc_tc: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  jcc_base: 0
  slo: 0
profile: jcc_tc
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
