<?php

/**
 * @file
 * Module hooks for jcc_courts_custom.
 */

use Drupal\Core\Queue\RequeueException;

/**
 * Citable opinions ultimate cron config callback.
 */
function jcc_courts_custom_migrate_opinions_citable() {
  $migration_id = 'courts_node_opinion_published';
  jcc_courts_custom_run_migration($migration_id, TRUE);
}

/**
 * Citable opinions with grant review ultimate cron config callback.
 */
function jcc_courts_custom_migrate_opinions_citable_review() {
  $migration_id = 'courts_node_opinion_published_review';
  jcc_courts_custom_run_migration($migration_id, TRUE);
}

/**
 * Citable opinions archived ultimate cron config callback.
 */
function jcc_courts_custom_migrate_opinions_citable_archive() {
  $migration_id = 'courts_node_opinion_published_archive';
  jcc_courts_custom_run_migration($migration_id, TRUE);
}

/**
 * Non-citable opinions ultimate cron config callback.
 */
function jcc_courts_custom_migrate_opinions_noncitable() {
  $migration_id = 'courts_node_opinion_unpublished';
  jcc_courts_custom_run_migration($migration_id, TRUE);
}

/**
 * Non-citable opinions with grant review ultimate cron config callback.
 */
function jcc_courts_custom_migrate_opinions_noncitable_review() {
  $migration_id = 'courts_node_opinion_unpublished_review';
  jcc_courts_custom_run_migration($migration_id, TRUE);
}

/**
 * Opinion citing media ultimate cron config callback.
 */
function jcc_courts_custom_migrate_opinions_citing_media() {
  $migration_id = 'courts_media_opinion_citing';
  jcc_courts_custom_run_migration($migration_id, TRUE);
}

/**
 * Opinion citing ultimate cron config callback.
 */
function jcc_courts_custom_migrate_opinions_citing() {
  $migration_id = 'courts_node_opinion_citing';
  jcc_courts_custom_run_migration($migration_id, TRUE);
}

/**
 * Job posts ultimate cron config callback.
 */
function jcc_courts_custom_migrate_job_posts() {
  $migration_id = 'courts_node_job';
  jcc_courts_custom_run_migration($migration_id, TRUE);
}

/**
 * Common migration function.
 */
function jcc_courts_custom_run_migration($migration_id, $sync_option = FALSE, $lease_time = 3600) {
  $queue = \Drupal::queue('migration_queue_worker');
  $queue_worker = \Drupal::service('plugin.manager.queue_worker')->createInstance('migration_queue_worker');

  // Create queue item.
  $data = [
    'migration_id' => $migration_id,
    'sync_option' => $sync_option,
  ];
  $queue->createItem($data);

  // Queue item managment.
  while ($item = $queue->claimItem($lease_time)) {
    try {
      $queue_worker->processItem($item->data);
      $queue->deleteItem($item);
    }
    catch (RequeueException $e) {
      // Item will be requeued automatically.
      $queue->releaseItem($item);
    }
    catch (\Exception $e) {
      // Critical failure - remove item and log error.
      \Drupal::logger('jcc_courts_custom')->error('Queue processing failed: @message', [
        '@message' => $e->getMessage(),
      ]);
      $queue->deleteItem($item);
    }
  }
}
