extlink_target: true
extlink_target_no_override: true
extlink_nofollow: true
extlink_follow_no_override: true
extlink_subdomains: true
extlink_alert: false
extlink_alert_text: 'This link will take you to an external web site. We are not responsible for their content.'
extlink_exclude: ''
extlink_include: ''
extlink_class: ext
extlink_label: '(link is external)'
extlink_img_class: true
extlink_css_exclude: ''
extlink_css_explicit: ''
extlink_mailto_class: mailto
extlink_mailto_label: '(link sends email)'
extlink_use_font_awesome: true
extlink_icon_placement: '0'
extlink_font_awesome_classes:
  links: 'fa fa-external-link'
  mailto: 'fa fa-envelope-o'
whitelisted_domains: {  }
_core:
  default_config_hash: qXZfD-9jvcrRBhytJXpMOrJGUqTV7eSEJ13h6R9wCAs
extlink_use_external_js_file: true
extlink_exclude_admin_routes: false
extlink_noreferrer: true
