features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://logo_0.png'
favicon:
  use_default: true
facebook: 'https://www.facebook.com/CaliforniaCourts/'
twitter: 'https://twitter.com/CalCourts'
youtube: 'https://www.youtube.com/californiacourts'
_core:
  default_config_hash: SmvBk92BEAUiEXDQEmBvuH0fRx-BmSLB3Y7_eqNPH-A
