icons_path: libraries/courtyard-artifact/2.x/source/_patterns/01-atoms/icon/icons.svg
icon_sets: "fa\r\nline-white\r\nline-dark"
_core:
  default_config_hash: nd_iBAaxxPvcw45yvf7B-yfESek1AsAtxyzMG9LuXPo
