#!/usr/bin/env bash

BASEDIR=$(dirname $(dirname $(realpath $0)))

command=$1
sites=$(ls -d $BASEDIR/web/sites/* | grep -v '\.' | sed "s#${BASEDIR}/web/sites/##")

shift

# Include color file.
. ${BASEDIR}/scripts/colors.sh

show_help() {
  echo -e "\nFleet commands run the same process on all sites in the ${P}web/sites${RE} directory. ${Y}\n(Assumes pantheon site names jcc-[site], i.e. jcc-colusa)${RE}"
  echo -e "\n${B}Valid commands are:${RE}"
  . ${BASEDIR}/scripts/.fleet/backup.sh --help
  . ${BASEDIR}/scripts/.fleet/db-pull.sh --help
  . ${BASEDIR}/scripts/.fleet/drush.sh --help
}

case $command in

  "backup")
    . ${BASEDIR}/scripts/.fleet/backup.sh
    ;;

  "db-pull")
    . ${BASEDIR}/scripts/.fleet/db-pull.sh
    ;;

  "drush")
    . ${BASEDIR}/scripts/.fleet/drush.sh
    ;;

  *)
    show_help
    exit
    ;;
esac

echo -e "\n${Y}Processes may be running in parallel in the background.${RE}\n"
echo -e "Use ${P}ps${RE} to see running processes; stdout will still be displayed."
