_core:
  default_config_hash: Urak5euEiGk2B1078TPlgfPJeWTxjzcNXVhldUGBVDc
always_save_userinfo: true
connect_existing_users: true
override_registration_settings: false
user_login_display: above
userinfo_mappings:
  timezone: zoneinfo
  metatag: 0
  role_change: 0
  path: 0
  field_last_password_reset: 0
  field_password_expiration: 0
