applies_admin_routes: true
include_home_segment: true
home_segment_title: 'Supreme Court'
home_segment_keep: false
include_title_segment: true
language_path_prefix_as_segment: false
use_menu_title_as_fallback: true
use_page_title_as_menu_title_fallback: false
remove_repeated_segments: true
term_hierarchy: false
absolute_paths: false
hide_single_home_item: true
title_from_page_when_available: true
include_invalid_paths: true
excluded_paths: ''
replaced_titles: ''
custom_paths: ''
segments_separator: null
title_segment_as_link: false
_core:
  default_config_hash: BsTN_Es55_ObKSpLqqMCKJ1gtKQcm1lUCHP6UCTxyvk
use_site_title: false
add_structured_data_json_ld: 0
capitalizator_mode: none
capitalizator_ignored_words: ''
capitalizator_forced_words: ''
capitalizator_forced_words_case_sensitivity: 0
capitalizator_forced_words_first_letter: 0
