_core:
  default_config_hash: D76-2mFk30BE93q5ofCLbxQLR_fjSij41DAb1WZyAx8
description:
  type: textfield
  length: 128
icon:
  directory: core/modules/file/icons
make_unused_managed_files_temporary: false
