_core:
  default_config_hash: RYZ4bbH6h17JsTLPw7Wxk-7yMPRFpsUiQIp4fNdTaDs
protect_all_forms: true
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: false
element_name: honeypot__submission
time_limit: 5
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_personal_form: false
  node_alert_form: false
  node_document_form: false
  node_event_form: false
  node_landing_page_form: false
  node_location_form: false
  node_news_form: false
  node_subpage_form: false
