favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: sites/supremecourt/logo.svg
  use_default: true
scheme: local
header_footer_variant: default
site_name_first: ''
site_name_second: ''
hat_shoe_text: ''
hat_shoe_url: ''
email: ''
facebook: ''
flickr: ''
linkedin: ''
rss: ''
twitter: ''
youtube: ''
hide_translation: 0
enable_twitter_embed: 0
