_core:
  default_config_hash: X8jLEfKCIINnbLrRvcDQaiRgyNVR3Jv0xW5RVYDutYE
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
  domains:
    en: ''
    es: ''
selected_langcode: site_default
