_core:
  default_config_hash: 09c5p92TXPjQP5WaxsO38IxeE2rjgms9wsOu-lkG1Q8
cache_strings: true
translate_english: false
javascript:
  directory: languages
translation:
  use_source: remote_and_local
  default_filename: '%project-%version.%language.po'
  default_server_pattern: 'https://ftp.drupal.org/files/translations/%core/%project/%project-%version.%language.po'
  overwrite_customized: false
  overwrite_not_customized: true
  update_interval_days: 0
  path: sites/default/files/inyo/translations
  import_enabled: true
