_core:
  default_config_hash: EKcTdpJlgbuw6vwQA88pEhJM58Fp60vr73LtYPO4nEo
theme: classy
defaults:
  sender: sendgrid_integration
  formatter: php_mail
modules:
  sendgrid_integration:
    none:
      sender: sendgrid_integration
      formatter: php_mail
