roles_settings:
  editor:
    display_name: Editor
    name: Editor
    weight: 0
    selected: false
  messaging_manager:
    display_name: 'Messaging manager'
    name: 'Messaging manager'
    weight: 0
    selected: false
  administrator:
    display_name: Administrator
    name: Administrator
    weight: 0
    selected: false
  authenticated:
    display_name: 'Authenticated user'
    name: 'Authenticated user'
    weight: 0
    selected: false
  manager:
    display_name: Manager
    name: Manager
    weight: 0
    selected: false
  translator:
    display_name: Translator
    name: Translator
    weight: 0
    selected: false
