_core:
  default_config_hash: JjB9Z9CPfCnEC5Ei7KMQ7SL5QxjPjbkf9geuzOZ4SSo
quick_checkout: true
anonymous_access: true
purge_finished: _never
respect_text_format: true
allowed_formats: {  }
word_count_exclude_tags: true
source_list_limit: 20
submit_job_item_on_cron: false
job_items_cron_limit: 50
