label: 'Agregar o editar un índice de Search API'
tips:
  search-api-index-form-name:
    label: 'Nombre del índice'
  search-api-index-form-datasources:
    label: 'Orígenes de datos'
  search-api-index-form-tracker:
    label: Rastreador
  search-api-index-form-server:
    label: Servidor
  search-api-index-form-description:
    label: 'Descripción del índice'
  search-api-index-form-options:
    label: 'Opciones avanzadas'
