label: 'Información sobre un índice'
tips:
  search-api-index-introduction:
    label: 'Información sobre un índice'
    body: 'Esta página muestra un resumen de un índice de búsqueda y su estado.'
  search-api-index-index-status:
    label: 'Estado del índice'
  search-api-index-status:
    label: Estado
    body: 'Muestra si el índice está actualmente activado o desactivado.'
  search-api-index-datasources:
    label: 'Orígenes de datos'
  search-api-index-tracker:
    label: Rastreador
  search-api-index-server:
    label: Servidor
  search-api-index-server-index-status:
    label: 'Estado del índice del servidor'
  search-api-index-index-now:
    label: 'Comience a indexar ahora'
  search-api-index-tracking:
    label: 'Rastrear elementos para el índice'
  search-api-index-reindex:
    label: 'Poner en cola todos los elementos para su reindexación'
  search-api-index-clear:
    label: 'Borrar todos los datos indexados'
