_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
    ar: ar
    zh-hans: zh-hans
    zh-hant: zh-hant
    fa: fa
    ko: ko
    pa: pa
    ru: ru
    fil: fil
    vi: vi
  domains:
    en: ''
    es: ''
    ar: ''
    zh-hans: ''
    zh-hant: ''
    fa: ''
    ko: ''
    pa: ''
    ru: ''
    fil: ''
    vi: ''
selected_langcode: site_default
