_core:
  default_config_hash: 6ynzArDptMgNVdAPodaYCxp1_iI3gS-5vLfl5M7H13M
hide_media_library_media_tab: false
hide_media_library_files_tab: false
hide_admin_toolbar_links: false
enable_combined_upload: true
combined_upload_media_types:
  file: file
  image: image
  publication: publication
