_core:
  default_config_hash: dbTmQpZpbWBaYBWZq7Wi3_z2sNJThyHQOpH_StY12g8
langcode: en
publish:
  state:
    published: published
unpublish:
  state:
    archived: archived
    draft: draft
archive:
  state:
    archived: archived
enable_dialog_node_edit_form: true
enable_dialog_admin_content: true
