#!/bin/bash

## Description: Initialize/reinstall tools needed for critical CSS.
## Usage: critical-install
## Example: ddev critical-install
## Aliases: critical:install,install-critical-tools,cri

#ddev-generated

#-------------------------- Helper functions -----------------------------------

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'
divider='===================================================\n'
critical_command='ddev critical-run'

# PROJECT_ROOT and DOCROOT are set as env variables in cli
FULL_THEME_PATH="/var/www/html/${DDEV_DOCROOT}/${THEME}"

#-------------------------- Execution ------------------------------------------

# Abort if anything fails
set -e

# Critical.
echo -e "🏥 ${yellow} Installing tools needed for Critical${NC} 🏥"
echo -e "${green}${divider}${NC}"
sudo apt-get --allow-releaseinfo-change update
sudo apt-get install -yq --no-install-recommends libgbm1 libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 libnss3
# Add this for M chips.
sudo apt-get install -yq --no-install-recommends chromium

# Move to the theme.
echo -e "🚀 ${yellow} To the theme!${NC} 🚀"
echo -e "${yellow} ${FULL_THEME_PATH}${NC}"
echo -e "${green}${divider}${NC}"
cd ${FULL_THEME_PATH}

# Runs NPM Install.
echo -e "🚧 ${yellow} Install NPM${NC} 🚧"
echo -e "${green}${divider}${NC}"
source ~/.nvm/nvm.sh
source ~/.bashrc
echo "NVM version: $(nvm --version)"
NODE_VERSION=$(cat ${FULL_THEME_PATH}/.nvmrc)
echo "Theme node version: ${NODE_VERSION}"
nvm install ${NODE_VERSION}
nvm alias default ${NODE_VERSION}
nvm use
npm ci --save patch-package

# Finish.
echo -e "🎉 Critical CSS Tools installed.${NC} 🎉"
echo -e "${NC}Run ${yellow}${critical_command}${NC} to compile critical css.${NC}"
echo -e "${green}${divider}${NC}"
