features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
scheme: base
header_footer_variant: default
site_name_first: 'Judicial Council of California'
site_name_second: 'Center for Judicial Education and Resources'
hat_shoe_text: 'Judicial Resource Network'
hat_shoe_url: 'https://jrn.courts.ca.gov'
email: ''
facebook: ''
flickr: ''
linkedin: ''
rss: ''
twitter: ''
youtube: ''
hide_was_this_helpful: 1
hide_translation: 0
show_google_translate: 0
no_search_results_heading: ''
no_search_results_message:
  value: ''
  format: snippet
header_body:
  value: ''
  format: full_html
news_default_seal: ''
