#uuid: 3846daaf-ac99-45f0-8fca-0ed9e33eca4b
langcode: en
status: true
dependencies: {  }
id: cjer_nonsecured_redirect
class: null
field_plugin_method: null
cck_plugin_method: null
migration_tags:
  - cjer
migration_group: cjer
label: 'CJER: Import path redirects'
source:
  plugin: url
  data_fetcher_plugin: http
  data_parser_plugin: google_sheets
  urls: ''
  item_selector: entry
  fields:
    -
      name: id
      label: 'Unique ID'
      selector: doc
    -
      name: page
      label: 'Page URL'
      selector: page
  ids:
    id:
      type: string
  constants:
    uri_prefix: 'internal:'
    document_path: /system/files/cjer/
    status_code: 301
process:
  pseudo_base_path:
    plugin: public_files_dir
  pseudo_destination_filename:
    -
      plugin: path_from_url
      source: doc
    -
      plugin: callback
      callable: basename
    -
      plugin: callback
      callable: urldecode
    -
      plugin: str_replace
      search: ' '
      replace: '-'
    -
      plugin: callback
      callable: strtolower
    -
      plugin: skip_on_empty
      method: process
      message: 'Could not create file from URL.'
  uid:
    plugin: default_value
    default_value: 1
  redirect_source/path:
    -
      plugin: callback
      callable: urldecode
      source: url
    -
      plugin: path_from_url
    -
      plugin: substr
      start: 1
  redirect_source/query: {  }
  redirect_redirect/uri:
    plugin: concat
    source:
      - constants/uri_prefix
      - constants/document_path
      - '@pseudo_destination_filename'
  status_code: constants/status_code
  language:
    plugin: default_value
    source: language
    default_value: en
destination:
  plugin: 'entity:redirect'
migration_dependencies:
  required: {  }
  optional:
    - cjer_nonsecured_files
