<?php

/**
 * @file
 * Hooks and functions for the JCC Video Embed module.
 */

use Drupal\video_embed_field\ProviderPluginManager;

/**
 * Implements hook_help().
 */
function jcc_video_embed_akamai_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jcc_video_embed_granicus module.
    case 'help.page.jcc_video_embed_akamai':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('JCC Video Embed for Akamai') . '</p>';
      return $output;

    default:
  }
}

function jcc_video_embed_akamai_video_embed_field_providers_alter(array &$providers) {
  $providers['akamai'] = [
    'id' => 'akamai',
    'title' => t('Akamai Video'),
    'description' => t('Embed Akamai videos.'),
    'class' => 'Drupal\jcc_video_embed_wistia_akamai\Plugin\video_embed_field\Provider\Akamai',
  ];

  $providers['akamai_audio'] = [
    'id' => 'akamai_audio',
    'title' => t('Akamai Audio'),
    'description' => t('Embed Akamai audio files.'),
    'class' => 'Drupal\jcc_video_embed_wistia_akamai\Plugin\video_embed_field\Provider\AkamaiAudio',
  ];
}