ignored_config_entities:
  - jcc_base.settings
  - openid_connect.settings.windows_aad
  - geocoder.geocoder_provider.bingmaps
  - system.site
  - extlink.settings
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
