_core:
  default_config_hash: xu0yG13sSQJcXrOJJqsn44W_hUWAIFHVlphrzxT2ycU
page_title: Sitemap
message:
  value: ''
  format: plain_text
plugins:
  book:
    enabled: false
    weight: -50
  'vocabulary:event_type':
    enabled: false
    weight: -49
    settings:
      title: 'Event Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:tags':
    enabled: false
    weight: -48
    settings:
      title: Tags
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:subject_matter':
    enabled: false
    weight: -47
    settings:
      title: 'Subject Matter'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:person_type':
    enabled: false
    weight: -46
    settings:
      title: 'Person Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:news_type':
    enabled: false
    weight: -45
    settings:
      title: 'News Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:multimedia_type':
    enabled: false
    weight: -44
    settings:
      title: 'Multimedia Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:media_tags':
    enabled: false
    weight: -43
    settings:
      title: 'Media tags'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:media_image_category':
    enabled: false
    weight: -42
    settings:
      title: 'Media image category'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:media_file_category':
    enabled: false
    weight: -41
    settings:
      title: 'Media file category'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:matters_served':
    enabled: false
    weight: -40
    settings:
      title: 'Matters Served'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:location_type':
    enabled: false
    weight: -39
    settings:
      title: 'Location Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:glossary':
    enabled: false
    weight: -38
    settings:
      title: Glossary
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:document_type':
    enabled: false
    weight: -37
    settings:
      title: 'Document Type'
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  frontpage:
    enabled: true
    weight: -36
    settings:
      title: 'Front page'
      rss: /rss.xml
  'vocabulary:division':
    enabled: false
    weight: -35
    settings:
      title: Division
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'vocabulary:department':
    enabled: false
    weight: -34
    settings:
      title: Department
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
  'menu:tools':
    enabled: false
    weight: -33
    settings:
      title: Tools
      show_disabled: false
  'menu:shoe':
    enabled: false
    weight: -32
    settings:
      title: Shoe
      show_disabled: false
  'menu:secondary-footer':
    enabled: false
    weight: -31
    settings:
      title: 'Secondary Footer'
      show_disabled: false
  'menu:main':
    enabled: true
    weight: -30
    settings:
      title: 'Main navigation'
      show_disabled: false
  'menu:hat':
    enabled: false
    weight: -28
    settings:
      title: Hat
      show_disabled: false
  'menu:footer':
    enabled: true
    weight: -29
    settings:
      title: Footer
      show_disabled: false
  'menu:featured-links':
    enabled: false
    weight: -27
    settings:
      title: 'Featured Links'
      show_disabled: false
  'menu:admin':
    enabled: false
    weight: -26
    settings:
      title: Administration
      show_disabled: false
  'menu:account':
    enabled: false
    weight: -25
    settings:
      title: 'User account menu'
      show_disabled: false
  'vocabulary:topics':
    enabled: false
    weight: -24
    settings:
      title: Topics
      show_description: false
      show_count: false
      term_depth: 9
      term_count_threshold: 0
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
include_css: true
