display:
  default:
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
      fields:
        filesize:
          label: Size
        status:
          label: Status
        count:
          label: 'Used in'
      filters:
        status:
          expose:
            label: Status
  page_2:
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
      fields:
        entity_label:
          label: Entity
