display:
  default:
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
      fields:
        operations:
          label: Operations
