label: Media
display:
  default:
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
      fields:
        bundle:
          label: Type
        status:
          label: Status
          settings:
            format_custom_true: Published
            format_custom_false: Unpublished
        operations:
          label: Operations
      filters:
        bundle:
          expose:
            label: Type
        status:
          group_info:
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        langcode:
          expose:
            label: Language
      title: Media
  media_page_list:
    display_title: Media
    display_options:
      menu:
        title: Media
