display:
  default:
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
      fields:
        status:
          label: Status
        operations:
          label: Operations
      filters:
        status:
          group_info:
            label: Status
