display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Submit
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
  news_list:
    display_options:
      exposed_form:
        options:
          submit_button: Submit
