display:
  default:
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
      filters:
        status:
          group_info:
            label: Published
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        langcode:
          expose:
            label: Language
      title: Media
  page:
    display_options:
      fields:
        delete_media:
          text: Delete
