<?php

/**
 * @file
 * Contains jcc_blocks2.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jcc_blocks2_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jcc_blocks2 module.
    case 'help.page.jcc_blocks2':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('JCC Custom 2') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function jcc_blocks2_theme() {
  return [
    'jcc_newsroomfeed' => [
      'variables' => [
        'title' => NULL,
        'feed' => NULL,
      ],
    ],
  ];
}
