label: Comentarios
description: 'Buscar y administrar comentarios.'
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          tags:
            previous: '‹ anterior'
            next: 'siguiente ›'
            first: '« primero'
            last: 'última »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        comment_bulk_form:
          action_title: Acción
        subject:
          label: Asunto
        name:
          label: Autor
        entity_id:
          label: 'Enviado en'
        changed:
          label: Actualizado
        operations:
          label: Operaciones
      filters:
        subject:
          expose:
            label: Asunto
        combine:
          expose:
            label: 'Nombre del autor'
        langcode:
          expose:
            label: Idioma
      title: Comentarios
      empty:
        area_text_custom:
          content: 'No hay comentarios disponibles.'
      use_more_text: más
  page_published:
    display_title: 'Comentarios publicados'
    display_options:
      menu:
        title: Comentarios
        description: 'Comentarios publicados'
      display_description: 'La lista de comentarios aprobados.'
  page_unapproved:
    display_title: 'Comentarios sin aprobar'
    display_options:
      menu:
        title: 'Comentarios sin aprobar'
        description: 'Comentarios no aprobados'
      display_description: 'La lista de comentarios no aprobados.'
      filters:
        subject:
          expose:
            label: Asunto
        combine:
          expose:
            label: 'Nombre de autor'
        langcode:
          expose:
            label: Idioma
      fields:
        comment_bulk_form:
          action_title: Acción
        subject:
          label: Asunto
        name:
          label: Autor
        entity_id:
          label: 'Enviado en'
        changed:
          label: Actualizado
        operations:
          label: Operaciones
