/**
 * Implements hook_install().
 */
function jcc_video_embed_granicus_install() {
  // Enable field_granicus_view_link_id where supported.
  $form_display = \Drupal::service('entity_display.repository')->getFormDisplay('paragraph', 'hero');
  $form_display_array = $form_display->toArray();
  if (isset($form_display) && in_array('field_granicus_view_link_id', $form_display_array['hidden'])) {
    $form_display->setComponent('field_granicus_view_link_id', ['type' => 'number'])->save();
  }
}
