xlsx.xlsx.*:
  type: config_entity
  label: 'Spreadsheet'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    module:
      type: string
      label: 'Module'
    mapping:
      type: mapping
      mapping:
        source:
          type: string
        source_name:
          type: string
        csv:
          type: mapping
        export:
          type: mapping
        export_only:
          type: boolean
        entity_mapping:
          type: mapping
        field_mapping:
          type: mapping
        sheet_columns:
          type: mapping
